#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Hand-compiled Pro Kabaddi League (PKL) + international kabaddi dataset.

Sources: official prokabaddi.com, Olympics.com, Wikipedia and major kabaddi
aggregators (myKhel, ESPN, Khel Now). Career aggregate totals are approximate —
official profiles publish only current-season figures, so all-time tallies are
reconstructed from public reporting and rounded. Season finals, winners, venues,
records and award winners are cross-verified.
"""

# ============================================================ TEAMS ===========
# slug -> data. titles = list of season numbers won.
TEAMS = {
    "patna-pirates": dict(
        name="Patna Pirates", name_hi="पटना पाइरेट्स", city="पटना", state="बिहार",
        est=2014, owner="राजेश वी. शाह (केवीएस एनर्जी एंड स्पोर्ट्स)",
        titles=[3, 4, 5], runner_up=[8, 11], color="#b91c1c",
        key=["pardeep-narwal", "monu-goyat", "sachin-tanwar", "devank-dalal"],
        tag="पीकेएल इतिहास की सबसे सफल टीम — लगातार तीन ख़िताब (सीज़न 3, 4, 5)।"),
    "dabang-delhi": dict(
        name="Dabang Delhi K.C.", name_hi="दबंग दिल्ली के.सी.", city="नई दिल्ली", state="दिल्ली",
        est=2014, owner="राधा कपूर (डूआईटी स्पोर्ट्स) — पीकेएल की एकमात्र महिला मालिक",
        titles=[8], runner_up=[7], color="#dc2626",
        key=["naveen-kumar", "ashu-malik", "vishal-bhardwaj", "sandeep-narwal"],
        tag="सीज़न 8 चैंपियन; नवीन कुमार के नेतृत्व में सबसे मज़बूत रेडिंग इकाइयों में से एक।"),
    "u-mumba": dict(
        name="U Mumba", name_hi="यू मुंबा", city="मुंबई", state="महाराष्ट्र",
        est=2014, owner="यूनिलेज़र वेंचर्स (रॉनी स्क्रूवाला)",
        titles=[2], runner_up=[1, 3], color="#f97316",
        key=["anup-kumar", "fazel-atrachali", "surinder-singh", "rishank-devadiga"],
        tag="अनुप कुमार की कप्तानी में सीज़न 2 के चैंपियन; पहले तीन सीज़न का सबसे स्थिर पक्ष।"),
    "jaipur-pink-panthers": dict(
        name="Jaipur Pink Panthers", name_hi="जयपुर पिंक पैंथर्स", city="जयपुर", state="राजस्थान",
        est=2014, owner="अभिषेक बच्चन",
        titles=[1, 9], runner_up=[4], color="#db2777",
        key=["arjun-deshwal", "sunil-kumar", "ankush-rathee", "deepak-niwas-hooda"],
        tag="उद्घाटन सीज़न (सीज़न 1) के चैंपियन और सीज़न 9 विजेता।"),
    "bengal-warriors": dict(
        name="Bengal Warriors", name_hi="बंगाल वॉरियर्स", city="कोलकाता", state="पश्चिम बंगाल",
        est=2014, owner="कैप्री स्पोर्ट्स",
        titles=[7], runner_up=[], color="#1d4ed8",
        key=["maninder-singh", "jang-kun-lee", "mohammad-nabibakhsh", "abozar-mighani"],
        tag="सीज़न 7 चैंपियन; मनिंदर सिंह की रेडिंग पर आधारित मज़बूत टीम।"),
    "tamil-thalaivas": dict(
        name="Tamil Thalaivas", name_hi="तमिल थलाइवाज़", city="चेन्नई", state="तमिलनाडु",
        est=2017, owner="मैग्नम स्पोर्ट्स (सचिन तेंदुलकर सहित निवेशक)",
        titles=[], runner_up=[], color="#facc15",
        key=["ajay-thakur", "narender", "nitesh-kumar", "sagar"],
        tag="सीज़न 5 में शामिल हुई फ़्रेंचाइज़ी; अजय ठाकुर इसके पहले स्टार रेडर।"),
    "telugu-titans": dict(
        name="Telugu Titans", name_hi="तेलुगु टाइटन्स", city="हैदराबाद", state="तेलंगाना",
        est=2014, owner="वीरा स्पोर्ट्स कंसोर्टियम",
        titles=[], runner_up=[], color="#facc15",
        key=["rahul-chaudhari", "siddharth-desai", "vishal-bhardwaj", "abozar-mighani"],
        tag="राहुल चौधरी की 'रेड मशीन' के लिए प्रसिद्ध — उद्घाटन टीम, पर अब तक ख़िताब नहीं।"),
    "puneri-paltan": dict(
        name="Puneri Paltan", name_hi="पुनेरी पलटन", city="पुणे", state="महाराष्ट्र",
        est=2014, owner="इंश्योरकोट स्पोर्ट्स",
        titles=[10], runner_up=[9], color="#f59e0b",
        key=["aslam-inamdar", "mohit-goyat", "mohammadreza-shadloui", "pankaj-mohite"],
        tag="सीज़न 10 में पहला ख़िताब; अस्लम इनामदार की कप्तानी में युवा भारतीय कोर।"),
    "bengaluru-bulls": dict(
        name="Bengaluru Bulls", name_hi="बेंगलुरु बुल्स", city="बेंगलुरु", state="कर्नाटक",
        est=2014, owner="कॉस्मिक ग्लोबल मीडिया",
        titles=[6], runner_up=[2], color="#dc2626",
        key=["rohit-kumar", "pawan-sehrawat", "saurabh-nandal", "bharat-hooda"],
        tag="सीज़न 6 चैंपियन; पवन सहरावत के 'हाई-फ़्लायर' अवतार का जन्मस्थान।"),
    "haryana-steelers": dict(
        name="Haryana Steelers", name_hi="हरियाणा स्टीलर्स", city="सोनीपत", state="हरियाणा",
        est=2017, owner="जेएसडब्ल्यू स्पोर्ट्स",
        titles=[11], runner_up=[10], color="#ea580c",
        key=["mohammadreza-shadloui", "vikash-kandola", "jaideep-dahiya", "naveen-kumar"],
        tag="सीज़न 11 में पहला ख़िताब; शादलोई की रक्षापंक्ति के दम पर चैंपियन।"),
    "up-yoddhas": dict(
        name="UP Yoddhas", name_hi="यूपी योद्धा", city="लखनऊ", state="उत्तर प्रदेश",
        est=2017, owner="जीएमआर स्पोर्ट्स",
        titles=[], runner_up=[], color="#16a34a",
        key=["nitin-tomar", "pardeep-narwal", "nitesh-kumar", "surender-gill"],
        tag="सीज़न 5 में शामिल; नितिन तोमर और बाद में प्रदीप नरवाल इसके प्रमुख रेडर रहे।"),
    "gujarat-giants": dict(
        name="Gujarat Giants", name_hi="गुजरात जायंट्स", city="अहमदाबाद", state="गुजरात",
        est=2017, owner="अडानी स्पोर्ट्सलाइन",
        titles=[], runner_up=[5, 6], color="#fb923c",
        key=["sunil-kumar", "sachin-tanwar", "parvesh-bhainswal", "rohit-gulia"],
        tag="पहले 'गुजरात फ़ॉर्च्यूनजायंट्स'; अपने पहले दो ही सीज़न (5, 6) में उपविजेता।"),
}

# ============================================================ SEASONS =========
# Each: num, year, champion, runner_up (team slugs), score, venue,
# top_raider (name, team slug, pts), top_defender, mvp.
SEASONS = [
    dict(num=1, year="2014", champion="jaipur-pink-panthers", runner_up="u-mumba",
         score="35–24", venue="सरदार वल्लभभाई पटेल इंडोर स्टेडियम, मुंबई",
         raider=("Anup Kumar", "u-mumba", 155), defender=("Manjeet Chhillar", "bengaluru-bulls", 51),
         mvp=("Anup Kumar", "u-mumba")),
    dict(num=2, year="2015", champion="u-mumba", runner_up="bengaluru-bulls",
         score="36–30", venue="एनएससीआई डोम, मुंबई",
         raider=("Kashiling Adake", "dabang-delhi", 114), defender=("Ravinder Pahal", "dabang-delhi", 60),
         mvp=("Manjeet Chhillar", "bengaluru-bulls")),
    dict(num=3, year="2016", champion="patna-pirates", runner_up="u-mumba",
         score="31–28", venue="त्यागराज स्पोर्ट्स कॉम्प्लेक्स, नई दिल्ली",
         raider=("Pardeep Narwal", "patna-pirates", 116), defender=("Manjeet Chhillar", "puneri-paltan", 61),
         mvp=("Rohit Kumar", "patna-pirates")),
    dict(num=4, year="2016", champion="patna-pirates", runner_up="jaipur-pink-panthers",
         score="37–29", venue="गाचीबोवली इंडोर स्टेडियम, हैदराबाद",
         raider=("Rahul Chaudhari", "telugu-titans", 124), defender=("Fazel Atrachali", "u-mumba", 62),
         mvp=("Rahul Chaudhari", "telugu-titans")),
    dict(num=5, year="2017", champion="patna-pirates", runner_up="gujarat-giants",
         score="55–38", venue="जवाहरलाल नेहरू इंडोर स्टेडियम, चेन्नई",
         raider=("Pardeep Narwal", "patna-pirates", 369), defender=("Surender Nada", "u-mumba", 80),
         mvp=("Pardeep Narwal", "patna-pirates")),
    dict(num=6, year="2018-19", champion="bengaluru-bulls", runner_up="gujarat-giants",
         score="38–33", venue="डोम @ एनएससीआई, मुंबई",
         raider=("Pawan Sehrawat", "bengaluru-bulls", 271), defender=("Nitesh Kumar", "up-yoddhas", 100),
         mvp=("Pawan Sehrawat", "bengaluru-bulls")),
    dict(num=7, year="2019", champion="bengal-warriors", runner_up="dabang-delhi",
         score="39–34", venue="ईकेए एरिना, अहमदाबाद",
         raider=("Pawan Sehrawat", "bengaluru-bulls", 346), defender=("Fazel Atrachali", "u-mumba", 76),
         mvp=("Naveen Kumar", "dabang-delhi")),
    dict(num=8, year="2021-22", champion="dabang-delhi", runner_up="patna-pirates",
         score="37–36", venue="शेरेटन ग्रैंड, बेंगलुरु (बायो-बबल)",
         raider=("Pawan Sehrawat", "bengaluru-bulls", 304), defender=("Mohammadreza Shadloui", "patna-pirates", 89),
         mvp=("Naveen Kumar", "dabang-delhi")),
    dict(num=9, year="2022", champion="jaipur-pink-panthers", runner_up="puneri-paltan",
         score="33–29", venue="द डोम, एनएससीआई, मुंबई",
         raider=("Bharat Hooda", "bengaluru-bulls", 279), defender=("Ankush Rathee", "jaipur-pink-panthers", 89),
         mvp=("Arjun Deshwal", "jaipur-pink-panthers")),
    dict(num=10, year="2023-24", champion="puneri-paltan", runner_up="haryana-steelers",
         score="28–25", venue="जीएमसी बालयोगी स्टेडियम, हैदराबाद",
         raider=("Ashu Malik", "dabang-delhi", 276), defender=("Mohammadreza Shadloui", "puneri-paltan", 99),
         mvp=("Aslam Inamdar", "puneri-paltan")),
    dict(num=11, year="2024", champion="haryana-steelers", runner_up="patna-pirates",
         score="32–23", venue="शिव छत्रपति स्पोर्ट्स कॉम्प्लेक्स, बालेवाड़ी, पुणे",
         raider=("Devank Dalal", "patna-pirates", 301), defender=("Nitesh Kumar", "tamil-thalaivas", 77),
         mvp=("Mohammadreza Shadloui", "haryana-steelers")),
]

# ============================================================ PLAYERS =========
# id, name, name_hi, role, nationality, teams (slugs), raid, tackle,
# super10, high5, seasons, matches, note_hi. total = raid + tackle.
def _p(id, name, name_hi, role, teams, raid=0, tackle=0, super10=0, high5=0,
       seasons="", matches=0, nat="भारत", note=""):
    return dict(id=id, name=name, name_hi=name_hi, role=role, nat=nat, teams=teams,
                raid=raid, tackle=tackle, total=raid + tackle, super10=super10,
                high5=high5, seasons=seasons, matches=matches, note=note)

PLAYERS = [
    # ---- raiders ----
    _p("pardeep-narwal", "Pardeep Narwal", "प्रदीप नरवाल", "raider",
       ["patna-pirates", "up-yoddhas", "bengaluru-bulls"], raid=1801, tackle=12,
       super10=88, seasons="2–11", matches=190,
       note="'डुबकी किंग' — पीकेएल इतिहास के सबसे महान रेडर। सर्वाधिक रेड अंक (1801) और सर्वाधिक सुपर 10 (88) का रिकॉर्ड। सीज़न 5 में 369 रेड अंक का अमर रिकॉर्ड बनाया।"),
    _p("maninder-singh", "Maninder Singh", "मनिंदर सिंह", "raider",
       ["jaipur-pink-panthers", "bengal-warriors", "patna-pirates"], raid=1528, tackle=10,
       super10=78, seasons="1, 5–11", matches=128,
       note="रेड अंक की सर्वकालिक सूची में दूसरे स्थान पर; बंगाल वॉरियर्स के सीज़न 7 ख़िताब के नायक। 1500 रेड अंक पार करने वाले दूसरे खिलाड़ी।"),
    _p("pawan-sehrawat", "Pawan Sehrawat", "पवन सहरावत", "raider",
       ["bengaluru-bulls", "tamil-thalaivas", "telugu-titans"], raid=1318, tackle=8,
       super10=70, seasons="5–11", matches=130,
       note="'हाई-फ़्लायर' — एक ही मैच में सर्वाधिक 39 रेड अंक का रिकॉर्ड (बनाम हरियाणा, सीज़न 7)। लगातार तीन सीज़न (6,7,8) के शीर्ष रेडर।"),
    _p("naveen-kumar", "Naveen Kumar", "नवीन कुमार", "raider",
       ["dabang-delhi", "haryana-steelers"], raid=1100, tackle=6,
       super10=66, seasons="6–11", matches=120,
       note="'नवीन एक्सप्रेस' — लगातार 28 सुपर 10 का रिकॉर्ड। दबंग दिल्ली को सीज़न 8 का पहला ख़िताब दिलाया और लगातार दो बार एमवीपी।"),
    _p("arjun-deshwal", "Arjun Deshwal", "अर्जुन देशवाल", "raider",
       ["u-mumba", "jaipur-pink-panthers", "tamil-thalaivas"], raid=1172, tackle=10,
       super10=52, seasons="6–11", matches=110,
       note="'रेड मशीन' — जयपुर पिंक पैंथर्स के सीज़न 9 ख़िताब के एमवीपी (296 रेड अंक)। 1000 रेड अंक तक दूसरा सबसे तेज़ पहुँचने वाला रेडर।"),
    _p("rahul-chaudhari", "Rahul Chaudhari", "राहुल चौधरी", "raider",
       ["telugu-titans", "tamil-thalaivas", "jaipur-pink-panthers"], raid=1100, tackle=20,
       super10=47, seasons="1–9", matches=172,
       note="'शोमैन' — पीकेएल में 500, 700 और 800 रेड अंक तक पहुँचने वाले पहले खिलाड़ी; तेलुगु टाइटन्स के दीर्घकालिक स्टार रेडर।"),
    _p("sachin-tanwar", "Sachin Tanwar", "सचिन तंवर", "raider",
       ["gujarat-giants", "patna-pirates", "tamil-thalaivas", "puneri-paltan"], raid=1034, tackle=12,
       super10=35, seasons="5–11", matches=145,
       note="1000 रेड अंक क्लब के सदस्य; 2022 एशियाई खेलों में भारत के स्वर्ण विजेता दल का हिस्सा।"),
    _p("ajay-thakur", "Ajay Thakur", "अजय ठाकुर", "raider",
       ["bengaluru-bulls", "puneri-paltan", "tamil-thalaivas"], raid=700, tackle=20,
       super10=22, seasons="1–7", matches=120,
       note="भारत के पूर्व कप्तान; 2016 कबड्डी विश्व कप के नायक और 2018 एशियाई खेलों में टीम के अगुआ। पद्मश्री व अर्जुन पुरस्कार से सम्मानित।"),
    _p("siddharth-desai", "Siddharth Desai", "सिद्धार्थ देसाई", "raider",
       ["u-mumba", "telugu-titans"], raid=695, tackle=8,
       super10=34, seasons="6–11", matches=95,
       note="सीज़न 6 में 218 रेड अंक — किसी डेब्यू खिलाड़ी द्वारा सर्वाधिक। तेलुगु टाइटन्स ने रिकॉर्ड बोली पर ख़रीदा।"),
    _p("vikash-kandola", "Vikash Kandola", "विकास कंडोला", "raider",
       ["haryana-steelers", "bengaluru-bulls", "telugu-titans"], raid=813, tackle=10,
       super10=26, seasons="6–11", matches=120,
       note="हरियाणा स्टीलर्स के प्रमुख रेडर और कप्तान; निरंतर बड़े रेड स्कोर के लिए जाने जाते हैं।"),
    _p("ashu-malik", "Ashu Malik", "आशु मलिक", "raider",
       ["dabang-delhi"], raid=882, tackle=34,
       super10=46, seasons="8–11", matches=105,
       note="सीज़न 10 के सर्वश्रेष्ठ रेडर (276 रेड अंक); दबंग दिल्ली के युवा रेडिंग कोर का चेहरा।"),
    _p("devank-dalal", "Devank Dalal", "देवांक दलाल", "raider",
       ["dabang-delhi", "patna-pirates", "bengal-warriors"], raid=578, tackle=6,
       super10=33, seasons="9–11", matches=80,
       note="सीज़न 11 के शीर्ष रेडर — 25 मैचों में 301 रेड अंक; प्रदीप नरवाल के बाद एक सीज़न में 300 अंक पार करने वाले पहले खिलाड़ी।"),
    _p("nitin-tomar", "Nitin Tomar", "नितिन तोमर", "raider",
       ["bengal-warriors", "puneri-paltan", "up-yoddhas"], raid=491, tackle=38,
       super10=14, seasons="3–10", matches=91,
       note="'यूपी का बाहुबली' — बाएँ कोने का रेडर; अपने समय की सबसे महँगी नीलामी बोलियों में से एक।"),
    _p("anup-kumar", "Anup Kumar", "अनुप कुमार", "raider",
       ["u-mumba", "jaipur-pink-panthers"], raid=527, tackle=64,
       super10=22, seasons="1–6", matches=91,
       note="'कैप्टन कूल' — यू मुंबा को सीज़न 2 का ख़िताब दिलाया; सीज़न 1 के शीर्ष रेडर व एमवीपी। 400 रेड अंक तक पहुँचने वाले पहले खिलाड़ी।"),
    _p("rohit-kumar", "Rohit Kumar", "रोहित कुमार", "raider",
       ["bengaluru-bulls"], raid=670, tackle=18,
       super10=25, seasons="3–10", matches=110,
       note="'फ़्रॉग जंप' — बेंगलुरु बुल्स की कप्तानी कर सीज़न 6 का एकमात्र ख़िताब दिलाया; सीज़न 3 के एमवीपी।"),
    _p("monu-goyat", "Monu Goyat", "मोनू गोयत", "raider",
       ["patna-pirates", "haryana-steelers", "tamil-thalaivas"], raid=584, tackle=41,
       super10=23, seasons="2–11", matches=130,
       note="अपने समय में सबसे महँगे बिकने वाले खिलाड़ी (₹1.51 करोड़); निरंतर रेडिंग प्रदर्शन।"),
    _p("rishank-devadiga", "Rishank Devadiga", "रिशांक देवड़िगा", "raider",
       ["u-mumba", "up-yoddhas", "bengal-warriors"], raid=625, tackle=47,
       super10=11, seasons="2–9", matches=120,
       note="यू मुंबा और यूपी योद्धा के अनुभवी रेडर; एक मैच में 28 रेड अंक का बड़ा प्रदर्शन।"),
    _p("aslam-inamdar", "Aslam Inamdar", "अस्लम इनामदार", "allrounder",
       ["puneri-paltan"], raid=480, tackle=65,
       super10=18, seasons="7–11", matches=100,
       note="पुनेरी पलटन को सीज़न 10 का पहला ख़िताब कप्तान के रूप में दिलाया और एमवीपी बने।"),
    _p("mohit-goyat", "Mohit Goyat", "मोहित गोयत", "raider",
       ["puneri-paltan"], raid=495, tackle=12,
       super10=15, seasons="7–11", matches=95,
       note="पुनेरी पलटन के लिए अस्लम इनामदार के साथ रेडिंग जोड़ी; डेब्यू सीज़न में 183 अंक।"),
    _p("kashiling-adake", "Kashiling Adake", "कशीलिंग अडके", "raider",
       ["dabang-delhi", "u-mumba", "bengaluru-bulls"], raid=561, tackle=14,
       super10=18, seasons="1–7", matches=105,
       note="सीज़न 2 के शीर्ष रेडर (114 रेड अंक); शुरुआती दौर के सबसे प्रभावी रेडरों में से एक।"),
    _p("sukesh-hegde", "Sukesh Hegde", "सुकेश हेगड़े", "raider",
       ["telugu-titans", "gujarat-giants", "tamil-thalaivas", "patna-pirates"], raid=471, tackle=16,
       super10=12, seasons="1–9", matches=115,
       note="कई फ़्रेंचाइज़ियों के लिए भरोसेमंद रेडर; आरंभिक सीज़न के नियमित प्रदर्शक।"),
    _p("k-prapanjan", "K. Prapanjan", "के. प्रपंजन", "raider",
       ["u-mumba", "telugu-titans", "tamil-thalaivas", "bengal-warriors", "haryana-steelers"],
       raid=440, tackle=14, super10=10, seasons="2–11", matches=115,
       note="तमिलनाडु से फुर्तीला रेडर; कई टीमों के साथ लंबा पीकेएल करियर।"),
    _p("rakesh-kumar", "Rakesh Kumar", "राकेश कुमार", "raider",
       ["patna-pirates", "u-mumba", "telugu-titans"], raid=179, tackle=20,
       super10=3, seasons="1–3", matches=45,
       note="'लायन जंप' — पीकेएल के पहले सीज़न के सबसे महँगे खिलाड़ी; भारतीय कबड्डी के दिग्गज।"),
    _p("jang-kun-lee", "Jang Kun Lee", "जांग कुन ली", "raider",
       ["bengal-warriors", "patna-pirates"], raid=474, tackle=25,
       super10=9, seasons="1–12", matches=108, nat="दक्षिण कोरिया",
       note="पीकेएल के सबसे सफल विदेशी रेडर; 400 रेड अंक पार करने वाले पहले विदेशी खिलाड़ी।"),
    _p("deepak-niwas-hooda", "Deepak Niwas Hooda", "दीपक निवास हुड्डा", "allrounder",
       ["telugu-titans", "puneri-paltan", "jaipur-pink-panthers"], raid=430, tackle=110,
       super10=12, high5=4, seasons="1–9", matches=130,
       note="भारत के लिए विश्व कप विजेता ऑल-राउंडर; रेडिंग और कप्तानी दोनों में योगदान।"),
    _p("bharat-hooda", "Bharat Hooda", "भरत हुड्डा", "raider",
       ["bengaluru-bulls", "puneri-paltan"], raid=420, tackle=10,
       super10=10, seasons="8–11", matches=70,
       note="सीज़न 9 के सर्वश्रेष्ठ रेडर पुरस्कार विजेता (279 रेड अंक)।"),
    _p("pankaj-mohite", "Pankaj Mohite", "पंकज मोहिते", "raider",
       ["puneri-paltan"], raid=380, tackle=20, super10=8, seasons="7–11", matches=80,
       note="पुनेरी पलटन के युवा रेडर; सीज़न 10 ख़िताबी अभियान का अहम हिस्सा।"),
    _p("guman-singh", "Guman Singh", "गुमान सिंह", "raider",
       ["tamil-thalaivas", "telugu-titans", "gujarat-giants"], raid=400, tackle=12,
       super10=11, seasons="6–11", matches=85, note="कई टीमों के लिए लगातार रेडिंग करने वाले युवा खिलाड़ी।"),
    _p("narender", "Narender", "नरेंद्र", "raider",
       ["tamil-thalaivas"], raid=360, tackle=10, super10=9, seasons="8–11", matches=70,
       note="तमिल थलाइवाज़ का तेज़ रेडर; सीज़न 9 का सर्वश्रेष्ठ युवा खिलाड़ी।"),
    _p("surender-gill", "Surender Gill", "सुरेंदर गिल", "raider",
       ["up-yoddhas", "haryana-steelers"], raid=420, tackle=8, super10=12, seasons="8–11", matches=80,
       note="यूपी योद्धा का प्रमुख रेडर; बड़े मुक़ाबलों में बड़े स्कोर के लिए जाने जाते हैं।"),
    _p("meetu", "Meetu", "मीतू", "raider",
       ["haryana-steelers", "telugu-titans"], raid=260, tackle=10, super10=5, seasons="8–11", matches=70,
       note="हरियाणा स्टीलर्स के रेडर; सीज़न 9 में सर्वश्रेष्ठ व्यक्तिगत प्रदर्शन।"),

    # ---- defenders ----
    _p("fazel-atrachali", "Fazel Atrachali", "फ़ज़ेल अत्राचली", "defender",
       ["u-mumba", "patna-pirates", "gujarat-giants", "puneri-paltan", "bengal-warriors"],
       tackle=597, raid=20, high5=30, seasons="2–12", matches=207, nat="ईरान",
       note="'सुल्तान' — सर्वाधिक टैकल अंक (597) के साथ सर्वकालिक नंबर 1 डिफेंडर; 500 टैकल अंक तक पहुँचने वाले पहले खिलाड़ी। शीर्ष-10 में एकमात्र विदेशी।"),
    _p("surjeet-singh", "Surjeet Singh", "सुरजीत सिंह", "defender",
       ["puneri-paltan", "u-mumba", "bengal-warriors", "tamil-thalaivas", "telugu-titans"],
       tackle=415, raid=12, high5=34, seasons="1–11", matches=190,
       note="सर्वाधिक टैकल अंक वाले भारतीय डिफेंडर; सर्वाधिक हाई 5 (34) का रिकॉर्ड। राइट कवर के माहिर।"),
    _p("manjeet-chhillar", "Manjeet Chhillar", "मंजीत छिल्लर", "defender",
       ["bengaluru-bulls", "puneri-paltan", "jaipur-pink-panthers", "tamil-thalaivas", "dabang-delhi"],
       tackle=391, raid=200, high5=25, seasons="1–8", matches=132,
       note="शानदार ऑल-राउंड खेल वाले डिफेंडर; लंबे समय तक सर्वाधिक टैकल अंक का रिकॉर्ड अपने नाम रखा। सीज़न 2 के एमवीपी।"),
    _p("girish-ernak", "Girish Maruti Ernak", "गिरीश एरनाक", "defender",
       ["patna-pirates", "puneri-paltan", "u-mumba"], tackle=362, high5=24, seasons="1–9", matches=147,
       note="बाएँ कोने के मज़बूत डिफेंडर; पुनेरी पलटन के पूर्व कप्तान और 2018 एशियाई खेलों के पदक विजेता।"),
    _p("sandeep-narwal", "Sandeep Narwal", "संदीप नरवाल", "allrounder",
       ["patna-pirates", "telugu-titans", "puneri-paltan", "u-mumba", "dabang-delhi"],
       tackle=328, raid=300, high5=10, seasons="1–10", matches=156,
       note="रक्षा और रेडिंग दोनों में योगदान देने वाले ऑल-राउंडर; सीज़न 3 के सर्वश्रेष्ठ डिफेंडर।"),
    _p("nitesh-kumar", "Nitesh Kumar", "नितेश कुमार", "defender",
       ["up-yoddhas", "bengal-warriors", "tamil-thalaivas"], tackle=400, high5=28, seasons="5–11", matches=150,
       note="एक सीज़न में 100 टैकल अंक तक पहुँचने वाले पहले डिफेंडर (सीज़न 6); सीज़न 11 के सर्वश्रेष्ठ डिफेंडर।"),
    _p("sunil-kumar", "Sunil Kumar", "सुनील कुमार", "defender",
       ["gujarat-giants", "jaipur-pink-panthers", "u-mumba"], tackle=343, high5=22, seasons="5–11", matches=130,
       note="पीकेएल के सबसे सफल कप्तानों में से एक; राइट कवर के दिग्गज और जयपुर के सीज़न 9 ख़िताब के कप्तान।"),
    _p("ravinder-pahal", "Ravinder Pahal", "रविंदर पहल", "defender",
       ["dabang-delhi", "gujarat-giants", "telugu-titans", "bengaluru-bulls", "puneri-paltan"],
       tackle=339, high5=23, seasons="1–11", matches=124,
       note="राइट कोने के घातक डिफेंडर; सीज़न 2 के सर्वश्रेष्ठ डिफेंडर और 300 टैकल अंक पार करने वाले शुरुआती खिलाड़ी।"),
    _p("vishal-bhardwaj", "Vishal Bhardwaj", "विशाल भारद्वाज", "defender",
       ["telugu-titans", "dabang-delhi", "puneri-paltan"], tackle=321, high5=23, seasons="3–11", matches=136,
       note="'एंकल असैसिन' — सर्वाधिक सुपर टैकल वाले डिफेंडरों में से एक; दबंग दिल्ली की रक्षापंक्ति का आधार।"),
    _p("mohammadreza-shadloui", "Mohammadreza Shadloui", "मोहम्मदरेज़ा शादलोई", "allrounder",
       ["patna-pirates", "puneri-paltan", "haryana-steelers"], tackle=300, raid=150, high5=14, seasons="8–11",
       matches=90, nat="ईरान",
       note="'शोस्टॉपर' — सीज़न 11 के एमवीपी; एक मैच में 16 टैकल अंक (8 सुपर टैकल) का रिकॉर्ड। 300 टैकल अंक तक सबसे तेज़।"),
    _p("surender-nada", "Surender Nada", "सुरेंदर नाडा", "defender",
       ["u-mumba", "haryana-steelers"], tackle=300, high5=20, seasons="1–9", matches=120,
       note="यू मुंबा की दीवार; सीज़न 5 के सर्वश्रेष्ठ डिफेंडर (80 टैकल अंक)। लेफ़्ट कोने के विशेषज्ञ।"),
    _p("jaideep-dahiya", "Jaideep Dahiya", "जयदीप दहिया", "defender",
       ["haryana-steelers"], tackle=240, high5=15, seasons="8–11", matches=90,
       note="हरियाणा स्टीलर्स के कप्तान और लेफ़्ट कवर डिफेंडर; सीज़न 11 ख़िताब के स्तंभ।"),
    _p("saurabh-nandal", "Saurabh Nandal", "सौरभ नंदल", "defender",
       ["bengaluru-bulls", "dabang-delhi"], tackle=240, high5=14, seasons="7–11", matches=105,
       note="राइट कोने के युवा डिफेंडर; बेंगलुरु बुल्स के पूर्व कप्तान।"),
    _p("ankush-rathee", "Ankush Rathee", "अंकुश राठी", "defender",
       ["jaipur-pink-panthers"], tackle=159, high5=9, seasons="9–11", matches=50,
       note="सीज़न 9 में किसी डेब्यू खिलाड़ी द्वारा सर्वाधिक 89 टैकल अंक — सर्वश्रेष्ठ डिफेंडर पुरस्कार।"),
    _p("sombir", "Sombir", "सोमबीर", "defender",
       ["telugu-titans", "dabang-delhi", "gujarat-giants"], tackle=195, high5=15, seasons="4–10", matches=108,
       note="अनुभवी कोने के डिफेंडर; कई टीमों के लिए स्थिर रक्षात्मक प्रदर्शन।"),
    _p("abozar-mighani", "Abozar Mighani", "अबोज़र मिघानी", "defender",
       ["gujarat-giants", "telugu-titans", "bengal-warriors", "up-yoddhas"], tackle=203, high5=12,
       seasons="5–10", matches=89, nat="ईरान",
       note="'स्माइलिंग असैसिन' — राइट कवर का ईरानी डिफेंडर; 2018 एशियाई खेलों में ईरान का स्वर्ण।"),
    _p("parvesh-bhainswal", "Parvesh Bhainswal", "परवेश भैंसवाल", "defender",
       ["gujarat-giants", "tamil-thalaivas"], tackle=210, high5=13, seasons="5–11", matches=100,
       note="गुजरात की रक्षापंक्ति का आधार; सर्वाधिक सुपर टैकल वाले डिफेंडरों में शामिल।"),
    _p("mohammad-nabibakhsh", "Mohammad Nabibakhsh", "मोहम्मद नबीबख़्श", "allrounder",
       ["bengal-warriors", "puneri-paltan"], raid=225, tackle=76, high5=3, super10=4, seasons="7–11",
       matches=95, nat="ईरान",
       note="बंगाल वॉरियर्स के सीज़न 7 ख़िताब का हिस्सा; रेडिंग और रक्षा दोनों में सक्षम ईरानी ऑल-राउंडर।"),
    _p("rohit-gulia", "Rohit Gulia", "रोहित गुलिया", "allrounder",
       ["gujarat-giants", "haryana-steelers"], raid=490, tackle=19, super10=12, seasons="5–11", matches=110,
       note="रेडिंग में माहिर ऑल-राउंडर; कई फ़्रेंचाइज़ियों के लिए उपयोगी खिलाड़ी।"),
    _p("meraj-sheykh", "Meraj Sheykh", "मेराज शेख़", "allrounder",
       ["dabang-delhi"], raid=330, tackle=130, super10=8, high5=4, seasons="1–7", matches=100, nat="ईरान",
       note="दबंग दिल्ली के पूर्व कप्तान और ईरानी ऑल-राउंडर; शुरुआती सीज़न के सबसे बहुमुखी विदेशी खिलाड़ी।"),
]

PLAYER_BY_ID = {p["id"]: p for p in PLAYERS}

# ============================================================ RECORDS =========
# label_hi -> list of (player_id_or_name, value, context_hi)
RECORDS = {
    "career_raid": ("सर्वाधिक रेड अंक (करियर)", [
        ("pardeep-narwal", 1801, "सीज़न 2–11"),
        ("maninder-singh", 1528, "सीज़न 1, 5–11"),
        ("pawan-sehrawat", 1318, "सीज़न 5–11"),
        ("arjun-deshwal", 1172, "सीज़न 6–11"),
        ("naveen-kumar", 1100, "सीज़न 6–11"),
        ("rahul-chaudhari", 1100, "सीज़न 1–9"),
        ("sachin-tanwar", 1034, "सीज़न 5–11"),
        ("vikash-kandola", 813, "सीज़न 6–11"),
        ("ashu-malik", 882, "सीज़न 8–11"),
        ("siddharth-desai", 695, "सीज़न 6–11"),
    ]),
    "career_tackle": ("सर्वाधिक टैकल अंक (करियर)", [
        ("fazel-atrachali", 597, "सीज़न 2–12"),
        ("surjeet-singh", 415, "सीज़न 1–11"),
        ("nitesh-kumar", 400, "सीज़न 5–11"),
        ("manjeet-chhillar", 391, "सीज़न 1–8"),
        ("girish-ernak", 362, "सीज़न 1–9"),
        ("sunil-kumar", 343, "सीज़न 5–11"),
        ("ravinder-pahal", 339, "सीज़न 1–11"),
        ("sandeep-narwal", 328, "सीज़न 1–10"),
        ("vishal-bhardwaj", 321, "सीज़न 3–11"),
        ("mohammadreza-shadloui", 300, "सीज़न 8–11"),
    ]),
    "career_super10": ("सर्वाधिक सुपर 10 (करियर)", [
        ("pardeep-narwal", 88, "रिकॉर्ड"),
        ("maninder-singh", 78, ""),
        ("pawan-sehrawat", 70, ""),
        ("naveen-kumar", 66, ""),
        ("arjun-deshwal", 52, ""),
        ("rahul-chaudhari", 47, ""),
        ("ashu-malik", 46, ""),
        ("sachin-tanwar", 35, ""),
        ("siddharth-desai", 34, ""),
        ("devank-dalal", 33, ""),
    ]),
    "career_high5": ("सर्वाधिक हाई 5 (करियर)", [
        ("surjeet-singh", 34, "रिकॉर्ड"),
        ("fazel-atrachali", 30, ""),
        ("nitesh-kumar", 28, ""),
        ("manjeet-chhillar", 25, ""),
        ("girish-ernak", 24, ""),
        ("vishal-bhardwaj", 23, ""),
        ("ravinder-pahal", 23, ""),
        ("sunil-kumar", 22, ""),
        ("surender-nada", 20, ""),
        ("sombir", 15, ""),
    ]),
}

# milestone-style single records: (label_hi, holder_hi, value_hi, detail_hi)
RECORD_MILESTONES = [
    ("एक मैच में सर्वाधिक रेड अंक", "पवन सहरावत", "39 अंक",
     "बेंगलुरु बुल्स बनाम हरियाणा स्टीलर्स (सीज़न 7) — टीम के सभी रेड अंक अकेले बनाए।"),
    ("एक सीज़न में सर्वाधिक रेड अंक", "प्रदीप नरवाल", "369 अंक",
     "सीज़न 5 में 26 मैचों में — आज भी अटूट रिकॉर्ड (पवन सहरावत 346 के साथ निकटतम)।"),
    ("एक मैच में सर्वाधिक टैकल अंक", "मोहम्मदरेज़ा चियानेह (शादलोई)", "16 अंक",
     "पटना पाइरेट्स बनाम दबंग दिल्ली (सीज़न 9) — जिसमें 8 सुपर टैकल शामिल।"),
    ("सर्वाधिक रेड अंक (करियर)", "प्रदीप नरवाल", "1801 अंक",
     "1800 रेड अंक पार करने वाले पहले और एकमात्र खिलाड़ी।"),
    ("सर्वाधिक टैकल अंक (करियर)", "फ़ज़ेल अत्राचली", "597 अंक",
     "500 टैकल अंक तक पहुँचने वाले पहले खिलाड़ी; शीर्ष-10 में एकमात्र विदेशी।"),
    ("सर्वाधिक सुपर 10 (करियर)", "प्रदीप नरवाल", "88",
     "मनिंदर सिंह (78) से 10 अधिक।"),
    ("लगातार सर्वाधिक सुपर 10", "नवीन कुमार", "28",
     "जुलाई 2019 से जनवरी 2022 तक लगातार 28 मैचों में सुपर 10।"),
    ("एक मैच में सर्वाधिक टीम स्कोर", "तमिल थलाइवाज़", "74 अंक",
     "बंगाल वॉरियर्स पर 74–37 की जीत (सीज़न 10), जिसमें 6 ऑल-आउट।"),
    ("सर्वाधिक ख़िताब (टीम)", "पटना पाइरेट्स", "3 ख़िताब",
     "लगातार सीज़न 3, 4 और 5 जीतकर हैट्रिक।"),
    ("सबसे लंबा विजय क्रम", "यू मुंबा", "11 मैच",
     "सीज़न 3 में लगातार 11 जीत।"),
]

# ============================================================ INTERNATIONAL ===
WORLD_CUP = [
    ("2004", "मुंबई, भारत", "भारत", "ईरान", "55–27"),
    ("2007", "पनवेल, भारत", "भारत", "ईरान", "29–19"),
    ("2016", "अहमदाबाद, भारत", "भारत", "ईरान", "38–29"),
]

ASIAN_GAMES_MEN = [
    ("1990", "भारत"), ("1994", "भारत"), ("1998", "भारत"), ("2002", "भारत"),
    ("2006", "भारत"), ("2010", "भारत"), ("2014", "भारत"), ("2018", "ईरान"),
    ("2022", "भारत"),
]
ASIAN_GAMES_WOMEN = [
    ("2010", "भारत", "थाईलैंड", "28–14"),
    ("2014", "भारत", "ईरान", "31–21"),
    ("2018", "ईरान", "भारत", "27–24"),
    ("2022", "भारत", "चीनी ताइपे", "26–25"),
]

# ============================================================ GLOSSARY ========
# Kabaddi terminology, used on the about / rules content.
GLOSSARY = [
    ("रेड (Raid)", "हमलावर खिलाड़ी (रेडर) विरोधी पाले में जाकर डिफेंडरों को छूकर अंक कमाने का प्रयास करता है।"),
    ("टैकल (Tackle)", "डिफेंडर रेडर को अपने पाले में रोककर उसे लौटने से पहले पकड़ लेते हैं।"),
    ("रेड अंक (Raid Point)", "रेडर द्वारा किसी डिफेंडर को छूकर या बोनस से कमाया गया अंक।"),
    ("टैकल अंक (Tackle Point)", "रेडर को सफलतापूर्वक रोकने पर डिफेंडिंग टीम को मिलने वाला अंक।"),
    ("सुपर रेड (Super Raid)", "एक ही रेड में 3 या अधिक अंक कमाना।"),
    ("सुपर टैकल (Super Tackle)", "जब पाले में 3 या कम डिफेंडर हों और वे रेडर को रोक दें — 1 अतिरिक्त अंक।"),
    ("सुपर 10 (Super 10)", "किसी रेडर द्वारा एक मैच में 10 या अधिक रेड अंक।"),
    ("हाई 5 (High 5)", "किसी डिफेंडर द्वारा एक मैच में 5 या अधिक टैकल अंक।"),
    ("ऑल-आउट (All Out)", "पूरी विरोधी टीम के आउट हो जाने पर 2 अतिरिक्त अंक मिलते हैं।"),
    ("बोनस अंक (Bonus Point)", "जब पाले में 6 या अधिक डिफेंडर हों, रेडर बोनस लाइन पार कर एक अंक कमा सकता है।"),
    ("डू-ऑर-डाई रेड", "लगातार दो ख़ाली रेड के बाद तीसरी रेड में अंक लाना अनिवार्य, वरना रेडर आउट।"),
    ("मैट (Court)", "खेल का मैदान 13×10 मीटर (पुरुष); प्रत्येक टीम में 7 खिलाड़ी मैट पर होते हैं।"),
]
