#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Hand-compiled Pro Kabaddi League (PKL) + international kabaddi dataset.

Sources: official prokabaddi.com, Olympics.com, Wikipedia and major kabaddi
aggregators (myKhel, ESPN, Khel Now). Career aggregate totals are approximate —
official profiles publish only current-season figures, so all-time tallies are
reconstructed from public reporting and rounded. Season finals, winners, venues,
records and award winners are cross-verified.
"""

# ============================================================ TEAMS ===========
# slug -> data. titles = list of season numbers won.
TEAMS = {
    "patna-pirates": dict(
        name="Patna Pirates", name_hi="पटना पाइरेट्स", city="पटना", state="बिहार",
        est=2014, owner="राजेश वी. शाह (केवीएस एनर्जी एंड स्पोर्ट्स)",
        titles=[3, 4, 5], runner_up=[8, 11], color="#b91c1c",
        key=["pardeep-narwal", "monu-goyat", "sachin-tanwar", "devank-dalal"],
        tag="पीकेएल इतिहास की सबसे सफल टीम — लगातार तीन ख़िताब (सीज़न 3, 4, 5)।"),
    "dabang-delhi": dict(
        name="Dabang Delhi K.C.", name_hi="दबंग दिल्ली के.सी.", city="नई दिल्ली", state="दिल्ली",
        est=2014, owner="राधा कपूर (डूआईटी स्पोर्ट्स) — पीकेएल की एकमात्र महिला मालिक",
        titles=[8, 12], runner_up=[7], color="#dc2626",
        key=["naveen-kumar", "ashu-malik", "fazel-atrachali", "vishal-bhardwaj"],
        tag="दो बार चैंपियन (सीज़न 8 और 12); सीज़न 12 का ख़िताब फ़ज़ेल अत्राचली की कप्तानी में घरेलू मैदान पर जीता।"),
    "u-mumba": dict(
        name="U Mumba", name_hi="यू मुंबा", city="मुंबई", state="महाराष्ट्र",
        est=2014, owner="यूनिलेज़र वेंचर्स (रॉनी स्क्रूवाला)",
        titles=[2], runner_up=[1, 3], color="#f97316",
        key=["anup-kumar", "fazel-atrachali", "surinder-singh", "rishank-devadiga"],
        tag="अनुप कुमार की कप्तानी में सीज़न 2 के चैंपियन; पहले तीन सीज़न का सबसे स्थिर पक्ष।"),
    "jaipur-pink-panthers": dict(
        name="Jaipur Pink Panthers", name_hi="जयपुर पिंक पैंथर्स", city="जयपुर", state="राजस्थान",
        est=2014, owner="अभिषेक बच्चन",
        titles=[1, 9], runner_up=[4], color="#db2777",
        key=["arjun-deshwal", "sunil-kumar", "ankush-rathee", "deepak-niwas-hooda"],
        tag="उद्घाटन सीज़न (सीज़न 1) के चैंपियन और सीज़न 9 विजेता।"),
    "bengal-warriors": dict(
        name="Bengal Warriors", name_hi="बंगाल वॉरियर्स", city="कोलकाता", state="पश्चिम बंगाल",
        est=2014, owner="कैप्री स्पोर्ट्स",
        titles=[7], runner_up=[], color="#1d4ed8",
        key=["maninder-singh", "jang-kun-lee", "mohammad-nabibakhsh", "abozar-mighani"],
        tag="सीज़न 7 चैंपियन; मनिंदर सिंह की रेडिंग पर आधारित मज़बूत टीम।"),
    "tamil-thalaivas": dict(
        name="Tamil Thalaivas", name_hi="तमिल थलाइवाज़", city="चेन्नई", state="तमिलनाडु",
        est=2017, owner="मैग्नम स्पोर्ट्स (सचिन तेंदुलकर सहित निवेशक)",
        titles=[], runner_up=[], color="#facc15",
        key=["ajay-thakur", "narender", "nitesh-kumar", "sagar"],
        tag="सीज़न 5 में शामिल हुई फ़्रेंचाइज़ी; अजय ठाकुर इसके पहले स्टार रेडर।"),
    "telugu-titans": dict(
        name="Telugu Titans", name_hi="तेलुगु टाइटन्स", city="हैदराबाद", state="तेलंगाना",
        est=2014, owner="वीरा स्पोर्ट्स कंसोर्टियम",
        titles=[], runner_up=[], color="#facc15",
        key=["rahul-chaudhari", "siddharth-desai", "vishal-bhardwaj", "abozar-mighani"],
        tag="राहुल चौधरी की 'रेड मशीन' के लिए प्रसिद्ध — उद्घाटन टीम, पर अब तक ख़िताब नहीं।"),
    "puneri-paltan": dict(
        name="Puneri Paltan", name_hi="पुनेरी पलटन", city="पुणे", state="महाराष्ट्र",
        est=2014, owner="इंश्योरकोट स्पोर्ट्स",
        titles=[10], runner_up=[9, 12], color="#f59e0b",
        key=["aslam-inamdar", "mohit-goyat", "pankaj-mohite", "akash-shinde"],
        tag="सीज़न 10 में पहला ख़िताब; अस्लम इनामदार की कप्तानी में युवा भारतीय कोर। सीज़न 12 में फिर उपविजेता।"),
    "bengaluru-bulls": dict(
        name="Bengaluru Bulls", name_hi="बेंगलुरु बुल्स", city="बेंगलुरु", state="कर्नाटक",
        est=2014, owner="कॉस्मिक ग्लोबल मीडिया",
        titles=[6], runner_up=[2], color="#dc2626",
        key=["rohit-kumar", "pawan-sehrawat", "saurabh-nandal", "bharat-hooda"],
        tag="सीज़न 6 चैंपियन; पवन सहरावत के 'हाई-फ़्लायर' अवतार का जन्मस्थान।"),
    "haryana-steelers": dict(
        name="Haryana Steelers", name_hi="हरियाणा स्टीलर्स", city="सोनीपत", state="हरियाणा",
        est=2017, owner="जेएसडब्ल्यू स्पोर्ट्स",
        titles=[11], runner_up=[10], color="#ea580c",
        key=["mohammadreza-shadloui", "vikash-kandola", "jaideep-dahiya", "naveen-kumar"],
        tag="सीज़न 11 में पहला ख़िताब; शादलोई की रक्षापंक्ति के दम पर चैंपियन।"),
    "up-yoddhas": dict(
        name="UP Yoddhas", name_hi="यूपी योद्धा", city="लखनऊ", state="उत्तर प्रदेश",
        est=2017, owner="जीएमआर स्पोर्ट्स",
        titles=[], runner_up=[], color="#16a34a",
        key=["nitin-tomar", "pardeep-narwal", "nitesh-kumar", "surender-gill"],
        tag="सीज़न 5 में शामिल; नितिन तोमर और बाद में प्रदीप नरवाल इसके प्रमुख रेडर रहे।"),
    "gujarat-giants": dict(
        name="Gujarat Giants", name_hi="गुजरात जायंट्स", city="अहमदाबाद", state="गुजरात",
        est=2017, owner="अडानी स्पोर्ट्सलाइन",
        titles=[], runner_up=[5, 6], color="#fb923c",
        key=["sunil-kumar", "sachin-tanwar", "parvesh-bhainswal", "rohit-gulia"],
        tag="पहले 'गुजरात फ़ॉर्च्यूनजायंट्स'; अपने पहले दो ही सीज़न (5, 6) में उपविजेता।"),
}

# ============================================================ SEASONS =========
# Each: num, year, champion, runner_up (team slugs), score, venue,
# top_raider (name, team slug, pts), top_defender, mvp.
SEASONS = [
    dict(num=1, year="2014", champion="jaipur-pink-panthers", runner_up="u-mumba",
         score="35–24", venue="सरदार वल्लभभाई पटेल इंडोर स्टेडियम, मुंबई",
         raider=("Anup Kumar", "u-mumba", 155), defender=("Manjeet Chhillar", "bengaluru-bulls", 51),
         mvp=("Anup Kumar", "u-mumba")),
    dict(num=2, year="2015", champion="u-mumba", runner_up="bengaluru-bulls",
         score="36–30", venue="एनएससीआई डोम, मुंबई",
         raider=("Kashiling Adake", "dabang-delhi", 114), defender=("Ravinder Pahal", "dabang-delhi", 60),
         mvp=("Manjeet Chhillar", "bengaluru-bulls")),
    dict(num=3, year="2016", champion="patna-pirates", runner_up="u-mumba",
         score="31–28", venue="त्यागराज स्पोर्ट्स कॉम्प्लेक्स, नई दिल्ली",
         raider=("Pardeep Narwal", "patna-pirates", 116), defender=("Manjeet Chhillar", "puneri-paltan", 61),
         mvp=("Rohit Kumar", "patna-pirates")),
    dict(num=4, year="2016", champion="patna-pirates", runner_up="jaipur-pink-panthers",
         score="37–29", venue="गाचीबोवली इंडोर स्टेडियम, हैदराबाद",
         raider=("Rahul Chaudhari", "telugu-titans", 124), defender=("Fazel Atrachali", "u-mumba", 62),
         mvp=("Rahul Chaudhari", "telugu-titans")),
    dict(num=5, year="2017", champion="patna-pirates", runner_up="gujarat-giants",
         score="55–38", venue="जवाहरलाल नेहरू इंडोर स्टेडियम, चेन्नई",
         raider=("Pardeep Narwal", "patna-pirates", 369), defender=("Surender Nada", "u-mumba", 80),
         mvp=("Pardeep Narwal", "patna-pirates")),
    dict(num=6, year="2018-19", champion="bengaluru-bulls", runner_up="gujarat-giants",
         score="38–33", venue="डोम @ एनएससीआई, मुंबई",
         raider=("Pawan Sehrawat", "bengaluru-bulls", 271), defender=("Nitesh Kumar", "up-yoddhas", 100),
         mvp=("Pawan Sehrawat", "bengaluru-bulls")),
    dict(num=7, year="2019", champion="bengal-warriors", runner_up="dabang-delhi",
         score="39–34", venue="ईकेए एरिना, अहमदाबाद",
         raider=("Pawan Sehrawat", "bengaluru-bulls", 346), defender=("Fazel Atrachali", "u-mumba", 76),
         mvp=("Naveen Kumar", "dabang-delhi")),
    dict(num=8, year="2021-22", champion="dabang-delhi", runner_up="patna-pirates",
         score="37–36", venue="शेरेटन ग्रैंड, बेंगलुरु (बायो-बबल)",
         raider=("Pawan Sehrawat", "bengaluru-bulls", 304), defender=("Mohammadreza Shadloui", "patna-pirates", 89),
         mvp=("Naveen Kumar", "dabang-delhi")),
    dict(num=9, year="2022", champion="jaipur-pink-panthers", runner_up="puneri-paltan",
         score="33–29", venue="द डोम, एनएससीआई, मुंबई",
         raider=("Bharat Hooda", "bengaluru-bulls", 279), defender=("Ankush Rathee", "jaipur-pink-panthers", 89),
         mvp=("Arjun Deshwal", "jaipur-pink-panthers")),
    dict(num=10, year="2023-24", champion="puneri-paltan", runner_up="haryana-steelers",
         score="28–25", venue="जीएमसी बालयोगी स्टेडियम, हैदराबाद",
         raider=("Ashu Malik", "dabang-delhi", 276), defender=("Mohammadreza Shadloui", "puneri-paltan", 99),
         mvp=("Aslam Inamdar", "puneri-paltan")),
    dict(num=11, year="2024", champion="haryana-steelers", runner_up="patna-pirates",
         score="32–23", venue="शिव छत्रपति स्पोर्ट्स कॉम्प्लेक्स, बालेवाड़ी, पुणे",
         raider=("Devank Dalal", "patna-pirates", 301), defender=("Nitesh Kumar", "tamil-thalaivas", 77),
         mvp=("Mohammadreza Shadloui", "haryana-steelers")),
    dict(num=12, year="2025", champion="dabang-delhi", runner_up="puneri-paltan",
         score="31–28", venue="त्यागराज इंडोर स्टेडियम, नई दिल्ली",
         raider=("Ayan Lohchab", "patna-pirates", 316), defender=("Navdeep", "patna-pirates", 73),
         mvp=("Fazel Atrachali", "dabang-delhi")),
]

# ============================================================ PLAYERS =========
# id, name, name_hi, role, nationality, teams (slugs), raid, tackle,
# super10, high5, seasons, matches, note_hi. total = raid + tackle.
def _p(id, name, name_hi, role, teams, raid=0, tackle=0, super10=0, high5=0,
       seasons="", matches=0, nat="भारत", note=""):
    return dict(id=id, name=name, name_hi=name_hi, role=role, nat=nat, teams=teams,
                raid=raid, tackle=tackle, total=raid + tackle, super10=super10,
                high5=high5, seasons=seasons, matches=matches, note=note)

PLAYERS = [
    # ---- raiders ----
    _p("pardeep-narwal", "Pardeep Narwal", "प्रदीप नरवाल", "raider",
       ["patna-pirates", "up-yoddhas", "bengaluru-bulls"], raid=1801, tackle=12,
       super10=88, seasons="2–11", matches=190,
       note="'डुबकी किंग' — पीकेएल इतिहास के सबसे महान रेडर। सर्वाधिक रेड अंक (1801) और सर्वाधिक सुपर 10 (88) का रिकॉर्ड। सीज़न 5 में 369 रेड अंक का अमर रिकॉर्ड बनाया।"),
    _p("maninder-singh", "Maninder Singh", "मनिंदर सिंह", "raider",
       ["jaipur-pink-panthers", "bengal-warriors", "patna-pirates"], raid=1528, tackle=10,
       super10=78, seasons="1, 5–11", matches=128,
       note="रेड अंक की सर्वकालिक सूची में दूसरे स्थान पर; बंगाल वॉरियर्स के सीज़न 7 ख़िताब के नायक। 1500 रेड अंक पार करने वाले दूसरे खिलाड़ी।"),
    _p("pawan-sehrawat", "Pawan Sehrawat", "पवन सहरावत", "raider",
       ["bengaluru-bulls", "tamil-thalaivas", "telugu-titans"], raid=1460, tackle=8,
       super10=73, seasons="5–12", matches=152,
       note="'हाई-फ़्लायर' — एक ही मैच में सर्वाधिक 39 रेड अंक का रिकॉर्ड (बनाम हरियाणा, सीज़न 7)। लगातार तीन सीज़न (6,7,8) के शीर्ष रेडर; पीकेएल इतिहास के सर्वकालिक सबसे महँगे खिलाड़ी (₹2.605 करोड़)।"),
    _p("naveen-kumar", "Naveen Kumar", "नवीन कुमार", "raider",
       ["dabang-delhi", "haryana-steelers"], raid=1240, tackle=6,
       super10=70, seasons="6–12", matches=142,
       note="'नवीन एक्सप्रेस' — लगातार 28 सुपर 10 का रिकॉर्ड। दबंग दिल्ली को सीज़न 8 और सीज़न 12 के ख़िताब दिलाने वाले प्रमुख रेडर; लगातार दो बार एमवीपी भी रहे।"),
    _p("arjun-deshwal", "Arjun Deshwal", "अर्जुन देशवाल", "raider",
       ["u-mumba", "jaipur-pink-panthers", "tamil-thalaivas"], raid=1381, tackle=10,
       super10=55, seasons="6–12", matches=132,
       note="'रेड मशीन' — जयपुर पिंक पैंथर्स के सीज़न 9 ख़िताब के एमवीपी (296 रेड अंक)। 1000 रेड अंक तक दूसरा सबसे तेज़ पहुँचने वाला रेडर; तमिल थलाइवाज़ के लिए सीज़न 12 में 200+ रेड अंक।"),
    _p("rahul-chaudhari", "Rahul Chaudhari", "राहुल चौधरी", "raider",
       ["telugu-titans", "tamil-thalaivas", "jaipur-pink-panthers"], raid=1100, tackle=20,
       super10=47, seasons="1–9", matches=172,
       note="'शोमैन' — पीकेएल में 500, 700 और 800 रेड अंक तक पहुँचने वाले पहले खिलाड़ी; तेलुगु टाइटन्स के दीर्घकालिक स्टार रेडर।"),
    _p("sachin-tanwar", "Sachin Tanwar", "सचिन तंवर", "raider",
       ["gujarat-giants", "patna-pirates", "tamil-thalaivas", "puneri-paltan"], raid=1034, tackle=12,
       super10=35, seasons="5–11", matches=145,
       note="1000 रेड अंक क्लब के सदस्य; 2022 एशियाई खेलों में भारत के स्वर्ण विजेता दल का हिस्सा।"),
    _p("ajay-thakur", "Ajay Thakur", "अजय ठाकुर", "raider",
       ["bengaluru-bulls", "puneri-paltan", "tamil-thalaivas"], raid=700, tackle=20,
       super10=22, seasons="1–7", matches=120,
       note="भारत के पूर्व कप्तान; 2016 कबड्डी विश्व कप के नायक और 2018 एशियाई खेलों में टीम के अगुआ। पद्मश्री व अर्जुन पुरस्कार से सम्मानित।"),
    _p("siddharth-desai", "Siddharth Desai", "सिद्धार्थ देसाई", "raider",
       ["u-mumba", "telugu-titans"], raid=695, tackle=8,
       super10=34, seasons="6–11", matches=95,
       note="सीज़न 6 में 218 रेड अंक — किसी डेब्यू खिलाड़ी द्वारा सर्वाधिक। तेलुगु टाइटन्स ने रिकॉर्ड बोली पर ख़रीदा।"),
    _p("vikash-kandola", "Vikash Kandola", "विकास कंडोला", "raider",
       ["haryana-steelers", "bengaluru-bulls", "telugu-titans"], raid=813, tackle=10,
       super10=26, seasons="6–11", matches=120,
       note="हरियाणा स्टीलर्स के प्रमुख रेडर और कप्तान; निरंतर बड़े रेड स्कोर के लिए जाने जाते हैं।"),
    _p("ashu-malik", "Ashu Malik", "आशु मलिक", "raider",
       ["dabang-delhi"], raid=1085, tackle=34,
       super10=52, seasons="8–12", matches=127,
       note="सीज़न 10 के सर्वश्रेष्ठ रेडर (276 रेड अंक); दबंग दिल्ली के रेडिंग कोर का चेहरा और सीज़न 12 ख़िताबी अभियान के अग्रणी रेडर। 1000 रेड अंक क्लब के सदस्य।"),
    _p("devank-dalal", "Devank Dalal", "देवांक दलाल", "raider",
       ["dabang-delhi", "patna-pirates", "bengal-warriors"], raid=849, tackle=6,
       super10=40, seasons="9–12", matches=96,
       note="सीज़न 11 के शीर्ष रेडर — 25 मैचों में 301 रेड अंक; प्रदीप नरवाल के बाद एक सीज़न में 300 अंक पार करने वाले पहले खिलाड़ी। सीज़न 12 में बंगाल वॉरियर्स के कप्तान के रूप में सिर्फ़ 16 मैचों में 271 रेड अंक और सबसे तेज़ 200 रेड अंक का रिकॉर्ड।"),
    _p("nitin-tomar", "Nitin Tomar", "नितिन तोमर", "raider",
       ["bengal-warriors", "puneri-paltan", "up-yoddhas"], raid=491, tackle=38,
       super10=14, seasons="3–10", matches=91,
       note="'यूपी का बाहुबली' — बाएँ कोने का रेडर; अपने समय की सबसे महँगी नीलामी बोलियों में से एक।"),
    _p("anup-kumar", "Anup Kumar", "अनुप कुमार", "raider",
       ["u-mumba", "jaipur-pink-panthers"], raid=527, tackle=64,
       super10=22, seasons="1–6", matches=91,
       note="'कैप्टन कूल' — यू मुंबा को सीज़न 2 का ख़िताब दिलाया; सीज़न 1 के शीर्ष रेडर व एमवीपी। 400 रेड अंक तक पहुँचने वाले पहले खिलाड़ी।"),
    _p("rohit-kumar", "Rohit Kumar", "रोहित कुमार", "raider",
       ["bengaluru-bulls"], raid=670, tackle=18,
       super10=25, seasons="3–10", matches=110,
       note="'फ़्रॉग जंप' — बेंगलुरु बुल्स की कप्तानी कर सीज़न 6 का एकमात्र ख़िताब दिलाया; सीज़न 3 के एमवीपी।"),
    _p("monu-goyat", "Monu Goyat", "मोनू गोयत", "raider",
       ["patna-pirates", "haryana-steelers", "tamil-thalaivas"], raid=584, tackle=41,
       super10=23, seasons="2–11", matches=130,
       note="अपने समय में सबसे महँगे बिकने वाले खिलाड़ी (₹1.51 करोड़); निरंतर रेडिंग प्रदर्शन।"),
    _p("rishank-devadiga", "Rishank Devadiga", "रिशांक देवड़िगा", "raider",
       ["u-mumba", "up-yoddhas", "bengal-warriors"], raid=625, tackle=47,
       super10=11, seasons="2–9", matches=120,
       note="यू मुंबा और यूपी योद्धा के अनुभवी रेडर; एक मैच में 28 रेड अंक का बड़ा प्रदर्शन।"),
    _p("aslam-inamdar", "Aslam Inamdar", "अस्लम इनामदार", "allrounder",
       ["puneri-paltan"], raid=480, tackle=65,
       super10=18, seasons="7–11", matches=100,
       note="पुनेरी पलटन को सीज़न 10 का पहला ख़िताब कप्तान के रूप में दिलाया और एमवीपी बने।"),
    _p("mohit-goyat", "Mohit Goyat", "मोहित गोयत", "raider",
       ["puneri-paltan"], raid=495, tackle=12,
       super10=15, seasons="7–11", matches=95,
       note="पुनेरी पलटन के लिए अस्लम इनामदार के साथ रेडिंग जोड़ी; डेब्यू सीज़न में 183 अंक।"),
    _p("kashiling-adake", "Kashiling Adake", "कशीलिंग अडके", "raider",
       ["dabang-delhi", "u-mumba", "bengaluru-bulls"], raid=561, tackle=14,
       super10=18, seasons="1–7", matches=105,
       note="सीज़न 2 के शीर्ष रेडर (114 रेड अंक); शुरुआती दौर के सबसे प्रभावी रेडरों में से एक।"),
    _p("sukesh-hegde", "Sukesh Hegde", "सुकेश हेगड़े", "raider",
       ["telugu-titans", "gujarat-giants", "tamil-thalaivas", "patna-pirates"], raid=471, tackle=16,
       super10=12, seasons="1–9", matches=115,
       note="कई फ़्रेंचाइज़ियों के लिए भरोसेमंद रेडर; आरंभिक सीज़न के नियमित प्रदर्शक।"),
    _p("k-prapanjan", "K. Prapanjan", "के. प्रपंजन", "raider",
       ["u-mumba", "telugu-titans", "tamil-thalaivas", "bengal-warriors", "haryana-steelers"],
       raid=440, tackle=14, super10=10, seasons="2–11", matches=115,
       note="तमिलनाडु से फुर्तीला रेडर; कई टीमों के साथ लंबा पीकेएल करियर।"),
    _p("rakesh-kumar", "Rakesh Kumar", "राकेश कुमार", "raider",
       ["patna-pirates", "u-mumba", "telugu-titans"], raid=179, tackle=20,
       super10=3, seasons="1–3", matches=45,
       note="'लायन जंप' — पीकेएल के पहले सीज़न के सबसे महँगे खिलाड़ी; भारतीय कबड्डी के दिग्गज।"),
    _p("jang-kun-lee", "Jang Kun Lee", "जांग कुन ली", "raider",
       ["bengal-warriors", "patna-pirates"], raid=474, tackle=25,
       super10=9, seasons="1–12", matches=108, nat="दक्षिण कोरिया",
       note="पीकेएल के सबसे सफल विदेशी रेडर; 400 रेड अंक पार करने वाले पहले विदेशी खिलाड़ी।"),
    _p("deepak-niwas-hooda", "Deepak Niwas Hooda", "दीपक निवास हुड्डा", "allrounder",
       ["telugu-titans", "puneri-paltan", "jaipur-pink-panthers"], raid=430, tackle=110,
       super10=12, high5=4, seasons="1–9", matches=130,
       note="भारत के लिए विश्व कप विजेता ऑल-राउंडर; रेडिंग और कप्तानी दोनों में योगदान।"),
    _p("bharat-hooda", "Bharat Hooda", "भरत हुड्डा", "raider",
       ["bengaluru-bulls", "puneri-paltan", "telugu-titans"], raid=650, tackle=10,
       super10=18, seasons="8–12", matches=92,
       note="सीज़न 9 के सर्वश्रेष्ठ रेडर पुरस्कार विजेता (279 रेड अंक); सीज़न 12 में तेलुगु टाइटन्स के अग्रणी रेडर (230 रेड अंक) और 600वाँ करियर रेड पूरा किया।"),
    _p("pankaj-mohite", "Pankaj Mohite", "पंकज मोहिते", "raider",
       ["puneri-paltan"], raid=380, tackle=20, super10=8, seasons="7–11", matches=80,
       note="पुनेरी पलटन के युवा रेडर; सीज़न 10 ख़िताबी अभियान का अहम हिस्सा।"),
    _p("guman-singh", "Guman Singh", "गुमान सिंह", "raider",
       ["tamil-thalaivas", "telugu-titans", "gujarat-giants"], raid=400, tackle=12,
       super10=11, seasons="6–11", matches=85, note="कई टीमों के लिए लगातार रेडिंग करने वाले युवा खिलाड़ी।"),
    _p("narender", "Narender", "नरेंद्र", "raider",
       ["tamil-thalaivas"], raid=360, tackle=10, super10=9, seasons="8–11", matches=70,
       note="तमिल थलाइवाज़ का तेज़ रेडर; सीज़न 9 का सर्वश्रेष्ठ युवा खिलाड़ी।"),
    _p("surender-gill", "Surender Gill", "सुरेंदर गिल", "raider",
       ["up-yoddhas", "haryana-steelers"], raid=420, tackle=8, super10=12, seasons="8–11", matches=80,
       note="यूपी योद्धा का प्रमुख रेडर; बड़े मुक़ाबलों में बड़े स्कोर के लिए जाने जाते हैं।"),
    _p("meetu", "Meetu", "मीतू", "raider",
       ["haryana-steelers", "telugu-titans"], raid=260, tackle=10, super10=5, seasons="8–11", matches=70,
       note="हरियाणा स्टीलर्स के रेडर; सीज़न 9 में सर्वश्रेष्ठ व्यक्तिगत प्रदर्शन।"),

    # ---- Season 12 breakout stars ----
    _p("ayan-lohchab", "Ayan Lohchab", "अयान लोहचब", "raider",
       ["patna-pirates"], raid=360, tackle=8, super10=16, seasons="11–12", matches=44,
       note="सीज़न 12 के सर्वश्रेष्ठ रेडर — सिर्फ़ अपने दूसरे सीज़न में 22 मैचों में 316 रेड अंक (16 सुपर 10)। पटना पाइरेट्स के युवा सनसनी; प्रदीप नरवाल और पवन सहरावत के बाद एक सीज़न में 300 रेड अंक पार करने वाले चुनिंदा रेडरों में।"),

    # ---- defenders ----
    _p("fazel-atrachali", "Fazel Atrachali", "फ़ज़ेल अत्राचली", "defender",
       ["u-mumba", "patna-pirates", "gujarat-giants", "puneri-paltan", "bengal-warriors", "dabang-delhi"],
       tackle=649, raid=20, high5=32, seasons="2–12", matches=228, nat="ईरान",
       note="'सुल्तान' — सर्वाधिक टैकल अंक (649) के साथ सर्वकालिक नंबर 1 डिफेंडर; 500 टैकल अंक तक पहुँचने वाले पहले खिलाड़ी। दबंग दिल्ली के कप्तान के रूप में सीज़न 12 का ख़िताब और एमवीपी — फ़ाइनल में निर्णायक टैकल भी इन्हीं का था।"),
    _p("surjeet-singh", "Surjeet Singh", "सुरजीत सिंह", "defender",
       ["puneri-paltan", "u-mumba", "bengal-warriors", "tamil-thalaivas", "telugu-titans"],
       tackle=415, raid=12, high5=34, seasons="1–11", matches=190,
       note="सर्वाधिक टैकल अंक वाले भारतीय डिफेंडर; सर्वाधिक हाई 5 (34) का रिकॉर्ड। राइट कवर के माहिर।"),
    _p("manjeet-chhillar", "Manjeet Chhillar", "मंजीत छिल्लर", "defender",
       ["bengaluru-bulls", "puneri-paltan", "jaipur-pink-panthers", "tamil-thalaivas", "dabang-delhi"],
       tackle=391, raid=200, high5=25, seasons="1–8", matches=132,
       note="शानदार ऑल-राउंड खेल वाले डिफेंडर; लंबे समय तक सर्वाधिक टैकल अंक का रिकॉर्ड अपने नाम रखा। सीज़न 2 के एमवीपी।"),
    _p("girish-ernak", "Girish Maruti Ernak", "गिरीश एरनाक", "defender",
       ["patna-pirates", "puneri-paltan", "u-mumba"], tackle=362, high5=24, seasons="1–9", matches=147,
       note="बाएँ कोने के मज़बूत डिफेंडर; पुनेरी पलटन के पूर्व कप्तान और 2018 एशियाई खेलों के पदक विजेता।"),
    _p("sandeep-narwal", "Sandeep Narwal", "संदीप नरवाल", "allrounder",
       ["patna-pirates", "telugu-titans", "puneri-paltan", "u-mumba", "dabang-delhi"],
       tackle=328, raid=300, high5=10, seasons="1–10", matches=156,
       note="रक्षा और रेडिंग दोनों में योगदान देने वाले ऑल-राउंडर; सीज़न 3 के सर्वश्रेष्ठ डिफेंडर।"),
    _p("nitesh-kumar", "Nitesh Kumar", "नितेश कुमार", "defender",
       ["up-yoddhas", "bengal-warriors", "tamil-thalaivas"], tackle=465, high5=31, seasons="5–12", matches=172,
       note="एक सीज़न में 100 टैकल अंक तक पहुँचने वाले पहले डिफेंडर (सीज़न 6); सीज़न 11 के सर्वश्रेष्ठ डिफेंडर और तमिल थलाइवाज़ की रक्षापंक्ति के स्तंभ।"),
    _p("sunil-kumar", "Sunil Kumar", "सुनील कुमार", "defender",
       ["gujarat-giants", "jaipur-pink-panthers", "u-mumba"], tackle=390, high5=24, seasons="5–12", matches=152,
       note="पीकेएल के सबसे सफल कप्तानों में से एक; राइट कवर के दिग्गज और जयपुर के सीज़न 9 ख़िताब के कप्तान। सीज़न 12 में यू मुंबा के लिए 'टैकल ऑफ़ द सीज़न' विजेता।"),
    _p("ravinder-pahal", "Ravinder Pahal", "रविंदर पहल", "defender",
       ["dabang-delhi", "gujarat-giants", "telugu-titans", "bengaluru-bulls", "puneri-paltan"],
       tackle=339, high5=23, seasons="1–11", matches=124,
       note="राइट कोने के घातक डिफेंडर; सीज़न 2 के सर्वश्रेष्ठ डिफेंडर और 300 टैकल अंक पार करने वाले शुरुआती खिलाड़ी।"),
    _p("vishal-bhardwaj", "Vishal Bhardwaj", "विशाल भारद्वाज", "defender",
       ["telugu-titans", "dabang-delhi", "puneri-paltan"], tackle=321, high5=23, seasons="3–11", matches=136,
       note="'एंकल असैसिन' — सर्वाधिक सुपर टैकल वाले डिफेंडरों में से एक; दबंग दिल्ली की रक्षापंक्ति का आधार।"),
    _p("mohammadreza-shadloui", "Mohammadreza Shadloui", "मोहम्मदरेज़ा शादलोई", "allrounder",
       ["patna-pirates", "puneri-paltan", "haryana-steelers", "gujarat-giants"], tackle=370, raid=160, high5=16, seasons="8–12",
       matches=112, nat="ईरान",
       note="'शोस्टॉपर' — सीज़न 11 के एमवीपी; एक मैच में 16 टैकल अंक (8 सुपर टैकल) का रिकॉर्ड। 300 टैकल अंक तक सबसे तेज़; सीज़न 12 की नीलामी में गुजरात जायंट्स ने ₹2.23 करोड़ में ख़रीदा।"),
    _p("surender-nada", "Surender Nada", "सुरेंदर नाडा", "defender",
       ["u-mumba", "haryana-steelers"], tackle=300, high5=20, seasons="1–9", matches=120,
       note="यू मुंबा की दीवार; सीज़न 5 के सर्वश्रेष्ठ डिफेंडर (80 टैकल अंक)। लेफ़्ट कोने के विशेषज्ञ।"),
    _p("jaideep-dahiya", "Jaideep Dahiya", "जयदीप दहिया", "defender",
       ["haryana-steelers"], tackle=308, high5=18, seasons="8–12", matches=112,
       note="हरियाणा स्टीलर्स के कप्तान और लेफ़्ट कवर डिफेंडर; सीज़न 11 ख़िताब के स्तंभ और सीज़न 12 में 68 टैकल अंक के साथ शीर्ष डिफेंडरों में।"),
    _p("saurabh-nandal", "Saurabh Nandal", "सौरभ नंदल", "defender",
       ["bengaluru-bulls", "dabang-delhi"], tackle=240, high5=14, seasons="7–11", matches=105,
       note="राइट कोने के युवा डिफेंडर; बेंगलुरु बुल्स के पूर्व कप्तान।"),
    _p("ankush-rathee", "Ankush Rathee", "अंकुश राठी", "defender",
       ["jaipur-pink-panthers"], tackle=159, high5=9, seasons="9–11", matches=50,
       note="सीज़न 9 में किसी डेब्यू खिलाड़ी द्वारा सर्वाधिक 89 टैकल अंक — सर्वश्रेष्ठ डिफेंडर पुरस्कार।"),
    _p("sombir", "Sombir", "सोमबीर", "defender",
       ["telugu-titans", "dabang-delhi", "gujarat-giants"], tackle=195, high5=15, seasons="4–10", matches=108,
       note="अनुभवी कोने के डिफेंडर; कई टीमों के लिए स्थिर रक्षात्मक प्रदर्शन।"),
    _p("abozar-mighani", "Abozar Mighani", "अबोज़र मिघानी", "defender",
       ["gujarat-giants", "telugu-titans", "bengal-warriors", "up-yoddhas"], tackle=203, high5=12,
       seasons="5–10", matches=89, nat="ईरान",
       note="'स्माइलिंग असैसिन' — राइट कवर का ईरानी डिफेंडर; 2018 एशियाई खेलों में ईरान का स्वर्ण।"),
    _p("parvesh-bhainswal", "Parvesh Bhainswal", "परवेश भैंसवाल", "defender",
       ["gujarat-giants", "tamil-thalaivas"], tackle=210, high5=13, seasons="5–11", matches=100,
       note="गुजरात की रक्षापंक्ति का आधार; सर्वाधिक सुपर टैकल वाले डिफेंडरों में शामिल।"),
    _p("mohammad-nabibakhsh", "Mohammad Nabibakhsh", "मोहम्मद नबीबख़्श", "allrounder",
       ["bengal-warriors", "puneri-paltan"], raid=225, tackle=76, high5=3, super10=4, seasons="7–11",
       matches=95, nat="ईरान",
       note="बंगाल वॉरियर्स के सीज़न 7 ख़िताब का हिस्सा; रेडिंग और रक्षा दोनों में सक्षम ईरानी ऑल-राउंडर।"),
    _p("rohit-gulia", "Rohit Gulia", "रोहित गुलिया", "allrounder",
       ["gujarat-giants", "haryana-steelers"], raid=490, tackle=19, super10=12, seasons="5–11", matches=110,
       note="रेडिंग में माहिर ऑल-राउंडर; कई फ़्रेंचाइज़ियों के लिए उपयोगी खिलाड़ी।"),
    _p("meraj-sheykh", "Meraj Sheykh", "मेराज शेख़", "allrounder",
       ["dabang-delhi"], raid=330, tackle=130, super10=8, high5=4, seasons="1–7", matches=100, nat="ईरान",
       note="दबंग दिल्ली के पूर्व कप्तान और ईरानी ऑल-राउंडर; शुरुआती सीज़न के सबसे बहुमुखी विदेशी खिलाड़ी।"),

    # ==================== expansion: S1–S11 roster (100+ players) ====================
    # ---- Patna Pirates ----
    _p("prashanth-kumar-rai", "Prashanth Kumar Rai", "प्रशांत कुमार राय", "raider",
       ["patna-pirates", "tamil-thalaivas", "u-mumba"], raid=300, tackle=20, super10=6, seasons="5–10", matches=95,
       note="अनुभवी रेडर; कई फ़्रेंचाइज़ियों के लिए नियमित रेड अंक जुटाने वाले खिलाड़ी।"),
    _p("sajin-c", "Sajin C", "साजिन सी", "allrounder",
       ["patna-pirates"], raid=120, tackle=90, super10=1, high5=1, seasons="8–11", matches=75,
       note="पटना पाइरेट्स के उपयोगी ऑल-राउंडर; रक्षा और बोनस रेडिंग दोनों में योगदान।"),
    _p("shubham-shinde", "Shubham Shinde", "शुभम शिंदे", "defender",
       ["puneri-paltan", "patna-pirates"], tackle=205, high5=9, seasons="7–11", matches=95,
       note="मराठी कवर डिफेंडर; पुनेरी पलटन और पटना की रक्षापंक्ति का हिस्सा।"),
    _p("neeraj-kumar", "Neeraj Kumar", "नीरज कुमार", "defender",
       ["patna-pirates"], tackle=150, high5=6, seasons="9–11", matches=60,
       note="पटना पाइरेट्स की रक्षापंक्ति के कोने के डिफेंडर।"),
    _p("navdeep", "Navdeep", "नवदीप", "defender",
       ["patna-pirates"], tackle=73, high5=6, seasons="12", matches=21,
       note="सीज़न 12 के सर्वश्रेष्ठ डिफेंडर — 21 मैचों में 73 टैकल अंक (8 सुपर टैकल)। पटना पाइरेट्स के युवा कवर डिफेंडर; नॉकआउट में लगातार चार हाई 5 का रिकॉर्ड।"),
    _p("ran-singh", "Ran Singh", "रण सिंह", "raider",
       ["patna-pirates", "bengaluru-bulls"], raid=240, tackle=12, super10=5, seasons="1–6", matches=85,
       note="पटना पाइरेट्स के शुरुआती ख़िताबी सीज़नों के कोने के रेडर।"),
    _p("anil-kumar-pp", "Anil Kumar", "अनिल कुमार", "defender",
       ["patna-pirates"], tackle=95, high5=4, seasons="8–9", matches=42,
       note="पटना पाइरेट्स के लिए खेलने वाले कवर डिफेंडर।"),
    _p("hadi-tajik", "Hadi Tajik", "हादी ताजिक", "defender",
       ["patna-pirates"], tackle=85, high5=3, seasons="9–10", matches=38, nat="ईरान",
       note="ईरान के कवर डिफेंडर; पटना पाइरेट्स की रक्षा का हिस्सा।"),

    # ---- Dabang Delhi ----
    _p("sandeep-dhull", "Sandeep Kumar Dhull", "संदीप कुमार ढुल", "defender",
       ["dabang-delhi"], tackle=235, high5=12, seasons="8–11", matches=92,
       note="दबंग दिल्ली के कप्तान और कवर डिफेंडर; सीज़न 8 के ख़िताब के अहम स्तंभ।"),
    _p("joginder-narwal", "Joginder Narwal", "जोगिंदर नरवाल", "defender",
       ["dabang-delhi", "bengaluru-bulls"], tackle=220, high5=9, seasons="1–8", matches=115,
       note="दबंग दिल्ली के पूर्व कप्तान; अनुभवी कवर डिफेंडर।"),
    _p("amit-hooda", "Amit Hooda", "अमित हुड्डा", "defender",
       ["dabang-delhi", "gujarat-giants", "bengaluru-bulls"], tackle=200, high5=9, seasons="2–8", matches=100,
       note="कोने के मज़बूत डिफेंडर; कई टीमों के लिए भरोसेमंद रक्षा।"),
    _p("vijay-malik", "Vijay Malik", "विजय मलिक", "raider",
       ["dabang-delhi", "patna-pirates", "gujarat-giants"], raid=360, tackle=14, super10=7, seasons="8–11", matches=78,
       note="दबंग दिल्ली के तेज़ रेडर; डू-ऑर-डाई रेड में भरोसेमंद।"),
    _p("krishan-dhull", "Krishan", "कृष्ण", "raider",
       ["dabang-delhi", "patna-pirates"], raid=150, tackle=10, super10=2, seasons="8–10", matches=55,
       note="युवा रेडर; डू-ऑर-डाई रेड में उपयोगी प्रदर्शन।"),
    _p("yogesh-dahiya", "Yogesh Dahiya", "योगेश दहिया", "defender",
       ["dabang-delhi"], tackle=85, high5=3, seasons="9–10", matches=42,
       note="दबंग दिल्ली के युवा कवर डिफेंडर।"),

    # ---- U Mumba ----
    _p("dharmaraj-cheralathan", "Dharmaraj Cheralathan", "धर्मराज चेरलाथन", "defender",
       ["u-mumba", "dabang-delhi", "bengaluru-bulls", "patna-pirates"], tackle=250, high5=10, seasons="1–7", matches=120,
       note="कबड्डी के सबसे उम्रदराज़ स्टार डिफेंडरों में से एक; यू मुंबा के सीज़न 2 ख़िताब का हिस्सा।"),
    _p("mohit-chhillar", "Mohit Chhillar", "मोहित छिल्लर", "defender",
       ["u-mumba", "bengaluru-bulls", "telugu-titans", "tamil-thalaivas"], tackle=270, high5=14, seasons="1–7", matches=115,
       note="भारत के स्टार कवर डिफेंडर; शुरुआती सीज़नों के सर्वाधिक टैकल वाले खिलाड़ियों में।"),
    _p("surinder-singh", "Surinder Singh", "सुरिंदर सिंह", "defender",
       ["u-mumba", "telugu-titans"], tackle=230, high5=11, seasons="5–9", matches=95,
       note="यू मुंबा के कप्तान और लेफ़्ट कवर डिफेंडर।"),
    _p("vishal-mane", "Vishal Mane", "विशाल माने", "defender",
       ["u-mumba", "dabang-delhi"], tackle=140, high5=6, seasons="1–5", matches=70,
       note="यू मुंबा के शुरुआती दौर के अनुभवी कवर डिफेंडर।"),
    _p("abhishek-singh", "Abhishek Singh", "अभिषेक सिंह", "raider",
       ["u-mumba"], raid=280, tackle=8, super10=6, seasons="7–10", matches=70,
       note="यू मुंबा के युवा रेडर; निरंतर बड़े रेड स्कोर के लिए जाने जाते हैं।"),
    _p("rohit-baliyan", "Rohit Baliyan", "रोहित बालियान", "raider",
       ["u-mumba", "up-yoddhas"], raid=200, tackle=8, super10=4, seasons="6–8", matches=58,
       note="यू मुंबा और यूपी योद्धा के लिए खेलने वाले फुर्तीले रेडर।"),
    _p("nilesh-salunke", "Nilesh Salunke", "निलेश साळुंके", "raider",
       ["u-mumba", "bengal-warriors"], raid=200, tackle=10, super10=4, seasons="1–6", matches=78,
       note="शुरुआती सीज़नों के महाराष्ट्रीय रेडर।"),
    _p("heidarali-ekrami", "Heidarali Ekrami", "हेदरअली एकरामी", "defender",
       ["u-mumba"], tackle=90, high5=4, seasons="10–11", matches=45, nat="ईरान",
       note="ईरान के कवर डिफेंडर; यू मुंबा की रक्षापंक्ति का हिस्सा।"),

    # ---- Jaipur Pink Panthers ----
    _p("abhishek-ks", "Abhishek KS", "अभिषेक केएस", "defender",
       ["jaipur-pink-panthers"], tackle=130, high5=6, seasons="9–11", matches=58,
       note="जयपुर पिंक पैंथर्स के सीज़न 9 ख़िताबी अभियान की रक्षापंक्ति का हिस्सा।"),
    _p("lucky-sharma", "Lucky Sharma", "लकी शर्मा", "defender",
       ["jaipur-pink-panthers"], tackle=120, high5=5, seasons="9–11", matches=55,
       note="जयपुर पिंक पैंथर्स के कवर डिफेंडर।"),
    _p("vishal-lather", "Vishal Lather", "विशाल लाठर", "defender",
       ["jaipur-pink-panthers"], tackle=90, high5=4, seasons="9–10", matches=40,
       note="जयपुर पिंक पैंथर्स के युवा कोने के डिफेंडर।"),
    _p("sunil-siddhgavali", "Sunil Siddhgavali", "सुनील सिद्धगवली", "raider",
       ["jaipur-pink-panthers", "telugu-titans"], raid=90, tackle=8, super10=1, seasons="6–7", matches=32,
       note="जयपुर और तेलुगु के लिए खेलने वाले सहायक रेडर।"),

    # ---- Bengal Warriors ----
    _p("gaurav-khatri", "Gaurav Khatri", "गौरव खत्री", "defender",
       ["bengal-warriors", "patna-pirates"], tackle=170, high5=7, seasons="5–9", matches=85,
       note="बंगाल वॉरियर्स के सीज़न 7 ख़िताब की रक्षापंक्ति का हिस्सा।"),
    _p("rinku-narwal", "Rinku Narwal", "रिंकू नरवाल", "defender",
       ["bengal-warriors", "telugu-titans"], tackle=180, high5=8, seasons="6–9", matches=80,
       note="बंगाल वॉरियर्स के कोने के मज़बूत डिफेंडर।"),
    _p("gholamabbas-korouki", "Gholamabbas Korouki", "गुलामअब्बास कोरूकी", "defender",
       ["bengal-warriors"], tackle=80, high5=3, seasons="6–7", matches=35, nat="ईरान",
       note="ईरान के कवर डिफेंडर; बंगाल वॉरियर्स की रक्षा का हिस्सा।"),
    _p("vaibhav-bw", "Vaibhav", "वैभव", "raider",
       ["bengal-warriors"], raid=130, tackle=8, super10=1, seasons="10–11", matches=38,
       note="बंगाल वॉरियर्स के युवा रेडर।"),
    _p("dong-geon-lee", "Dong Geon Lee", "डोंग ग्यून ली", "raider",
       ["tamil-thalaivas", "gujarat-giants", "u-mumba", "bengaluru-bulls"], raid=127, tackle=2, super10=2,
       seasons="5–9", matches=55, nat="दक्षिण कोरिया",
       note="दक्षिण कोरिया के रेडर; सीज़न 9 में गुजरात जायंट्स के स्टैंड-इन कप्तान और 2016 विश्व कप में भारत को हराने वाली कोरियाई टीम का हिस्सा।"),

    # ---- Tamil Thalaivas ----
    _p("v-ajith-kumar", "V. Ajith Kumar", "वी. अजित कुमार", "raider",
       ["tamil-thalaivas"], raid=320, tackle=10, super10=8, seasons="8–11", matches=80,
       note="तमिल थलाइवाज़ के युवा स्टार रेडर; तेज़ रेडिंग के लिए जाने जाते हैं।"),
    _p("ajinkya-pawar", "Ajinkya Pawar", "अजिंक्य पवार", "raider",
       ["tamil-thalaivas", "u-mumba"], raid=220, tackle=10, super10=4, seasons="6–9", matches=62,
       note="तमिल थलाइवाज़ और यू मुंबा के लिए खेलने वाले रेडर।"),
    _p("sagar-tt", "Sagar", "सागर", "defender",
       ["tamil-thalaivas", "dabang-delhi"], tackle=180, high5=8, seasons="8–11", matches=80,
       note="तमिल थलाइवाज़ की रक्षा का कोने का डिफेंडर।"),
    _p("jeeva-kumar", "Jeeva Kumar", "जीवा कुमार", "defender",
       ["tamil-thalaivas", "telugu-titans", "patna-pirates"], tackle=200, high5=9, seasons="1–7", matches=100,
       note="अनुभवी कवर डिफेंडर; भारत के लिए अंतरराष्ट्रीय कबड्डी में योगदान।"),
    _p("himanshu-tt", "Himanshu Singh", "हिमांशु सिंह", "raider",
       ["tamil-thalaivas"], raid=90, tackle=6, super10=0, seasons="10–11", matches=30,
       note="तमिल थलाइवाज़ के युवा रेडर।"),
    _p("visvanath-v", "Visvanath V", "विश्वनाथ वी", "defender",
       ["tamil-thalaivas"], tackle=80, high5=3, seasons="10–11", matches=36,
       note="तमिल थलाइवाज़ के युवा कोने के डिफेंडर।"),

    # ---- Telugu Titans ----
    _p("manjeet-tt", "Manjeet", "मनजीत", "raider",
       ["telugu-titans", "dabang-delhi"], raid=420, tackle=12, super10=12, seasons="7–11", matches=90,
       note="तेलुगु टाइटन्स के प्रमुख रेडर; सीज़न 9 में शानदार रेडिंग प्रदर्शन।"),
    _p("suraj-desai", "Suraj Desai", "सूरज देसाई", "raider",
       ["telugu-titans", "u-mumba"], raid=130, tackle=8, super10=1, seasons="8–10", matches=45,
       note="सिद्धार्थ देसाई के भाई; तेलुगु टाइटन्स के सहायक रेडर।"),
    _p("rakesh-gowda", "Rakesh Gowda", "राकेश गौड़ा", "raider",
       ["telugu-titans", "bengaluru-bulls"], raid=120, tackle=10, super10=1, seasons="5–7", matches=45,
       note="तेलुगु टाइटन्स और बेंगलुरु बुल्स के लिए खेलने वाले रेडर।"),
    _p("sandeep-kandola", "Sandeep Kandola", "संदीप कंडोला", "defender",
       ["telugu-titans", "jaipur-pink-panthers"], tackle=120, high5=5, seasons="9–11", matches=55,
       note="तेलुगु टाइटन्स के कवर डिफेंडर।"),
    _p("vinod-kumar", "Vinod Kumar", "विनोद कुमार", "defender",
       ["up-yoddhas", "telugu-titans"], tackle=180, high5=8, seasons="7–10", matches=80,
       note="यूपी योद्धा और तेलुगु टाइटन्स की रक्षापंक्ति के अनुभवी डिफेंडर।"),
    _p("hadi-oshtorak", "Hadi Oshtorak", "हादी ओश्तोराक", "defender",
       ["telugu-titans", "patna-pirates", "u-mumba", "gujarat-giants"], raid=25, tackle=127, high5=3,
       seasons="2–8", matches=93, nat="ईरान",
       note="ईरान के अनुभवी कवर डिफेंडर; सीज़न 4 में पटना पाइरेट्स के ख़िताब और 2018 एशियाई खेलों में ईरान के स्वर्ण का हिस्सा।"),

    # ---- Puneri Paltan ----
    _p("sanjay-shrestha", "Sanjay", "संजय", "raider",
       ["puneri-paltan", "dabang-delhi"], raid=220, tackle=10, super10=5, seasons="9–11", matches=58,
       note="पुनेरी पलटन के युवा रेडर; सीज़न 9 के सर्वश्रेष्ठ डेब्यू खिलाड़ियों में।"),
    _p("akash-shinde", "Akash Shinde", "आकाश शिंदे", "raider",
       ["puneri-paltan", "tamil-thalaivas"], raid=200, tackle=10, super10=4, seasons="9–11", matches=55,
       note="पुनेरी पलटन के सीज़न 10 ख़िताबी अभियान के अहम रेडर।"),
    _p("abinesh-nadarajan", "Abinesh Nadarajan", "अबिनेश नादराजन", "defender",
       ["puneri-paltan", "gujarat-giants"], tackle=150, high5=6, seasons="8–11", matches=70,
       note="पुनेरी पलटन की रक्षापंक्ति के कोने के डिफेंडर।"),

    # ---- Bengaluru Bulls ----
    _p("chandran-ranjit", "Chandran Ranjit", "चंद्रन रंजीत", "raider",
       ["u-mumba", "bengaluru-bulls"], raid=250, tackle=10, super10=5, seasons="6–9", matches=70,
       note="यू मुंबा और बेंगलुरु बुल्स के लिए खेलने वाले फुर्तीले रेडर।"),
    _p("neeraj-narwal", "Neeraj Narwal", "नीरज नरवाल", "raider",
       ["bengaluru-bulls", "gujarat-giants"], raid=160, tackle=8, super10=3, seasons="8–10", matches=50,
       note="बेंगलुरु बुल्स के सहायक रेडर।"),
    _p("ashish-sangwan", "Ashish Sangwan", "आशीष सांगवान", "defender",
       ["bengaluru-bulls", "up-yoddhas"], tackle=120, high5=5, seasons="7–9", matches=55,
       note="बेंगलुरु बुल्स की रक्षापंक्ति के कोने के डिफेंडर।"),
    _p("rahul-sethpal", "Rahul Sethpal", "राहुल सेठपाल", "defender",
       ["bengaluru-bulls", "dabang-delhi"], tackle=140, high5=6, seasons="8–11", matches=70,
       note="बेंगलुरु बुल्स और दबंग दिल्ली के लिए खेलने वाले कवर डिफेंडर।"),
    _p("deepak-sankar", "Deepak Sankar", "दीपक शंकर", "defender",
       ["bengaluru-bulls"], tackle=64, high5=5, seasons="12", matches=19,
       note="सीज़न 12 के सर्वश्रेष्ठ उभरते युवा खिलाड़ी — डेब्यू सीज़न में 19 मैचों में 64 टैकल अंक (5 हाई 5)। बेंगलुरु बुल्स की रक्षापंक्ति के कोने के डिफेंडर।"),

    # ---- Haryana Steelers ----
    _p("sumit-haryana", "Sumit", "सुमित", "defender",
       ["haryana-steelers", "u-mumba"], tackle=200, high5=9, seasons="6–9", matches=85,
       note="हरियाणा स्टीलर्स की रक्षापंक्ति के अनुभवी कवर डिफेंडर।"),
    _p("vinay-hs", "Vinay", "विनय", "defender",
       ["haryana-steelers"], tackle=110, high5=5, seasons="9–11", matches=55,
       note="हरियाणा स्टीलर्स के युवा कोने के डिफेंडर।"),
    _p("mohit-nandal", "Mohit Nandal", "मोहित नंदल", "defender",
       ["haryana-steelers"], tackle=90, high5=4, seasons="10–11", matches=35,
       note="हरियाणा स्टीलर्स की रक्षा का युवा डिफेंडर।"),
    _p("sachin-vittala", "Sachin Vittala", "सचिन विट्ठल", "raider",
       ["haryana-steelers"], raid=150, tackle=8, super10=2, seasons="10–11", matches=42,
       note="हरियाणा स्टीलर्स के युवा रेडर।"),
    _p("aman-hs", "Aman", "अमन", "defender",
       ["haryana-steelers", "jaipur-pink-panthers"], tackle=160, high5=7, seasons="8–11", matches=72,
       note="हरियाणा और जयपुर के लिए खेलने वाले कवर डिफेंडर।"),

    # ---- UP Yoddhas ----
    _p("rohit-rana", "Rohit Rana", "रोहित राणा", "defender",
       ["up-yoddhas", "dabang-delhi"], tackle=160, high5=7, seasons="5–8", matches=75,
       note="यूपी योद्धा की रक्षापंक्ति के अनुभवी कवर डिफेंडर।"),
    _p("deepak-narwal", "Deepak Narwal", "दीपक नरवाल", "raider",
       ["up-yoddhas", "patna-pirates"], raid=200, tackle=10, super10=4, seasons="6–9", matches=65,
       note="यूपी योद्धा और पटना के लिए खेलने वाले रेडर।"),
    _p("ankit-beniwal", "Ankit Beniwal", "अंकित बेनीवाल", "raider",
       ["up-yoddhas"], raid=150, tackle=8, super10=2, seasons="8–10", matches=48,
       note="यूपी योद्धा के युवा रेडर।"),
    _p("gulveer-singh", "Gulveer Singh", "गुलवीर सिंह", "raider",
       ["up-yoddhas", "gujarat-giants"], raid=130, tackle=8, super10=1, seasons="7–9", matches=42,
       note="यूपी योद्धा और गुजरात के सहायक रेडर।"),
    _p("shrikant-tewthia", "Shrikant Tewthia", "श्रीकांत तेवतिया", "raider",
       ["up-yoddhas", "jaipur-pink-panthers"], raid=150, tackle=10, super10=3, seasons="5–7", matches=55,
       note="शुरुआती सीज़नों के अनुभवी रेडर।"),
    _p("ashu-singh", "Ashu Singh", "आशु सिंह", "defender",
       ["up-yoddhas"], tackle=100, high5=4, seasons="8–10", matches=45,
       note="यूपी योद्धा के कोने के डिफेंडर।"),

    # ---- Gujarat Giants ----
    _p("mahender-singh", "Mahender Singh", "महेंद्र सिंह", "defender",
       ["gujarat-giants", "jaipur-pink-panthers"], tackle=230, high5=12, seasons="5–9", matches=95,
       note="गुजरात जायंट्स की रक्षापंक्ति के कप्तान-स्तर के कवर डिफेंडर।"),
    _p("shrikant-jadhav", "Shrikant Jadhav", "श्रीकांत जाधव", "raider",
       ["gujarat-giants", "telugu-titans"], raid=360, tackle=25, super10=8, seasons="5–10", matches=95,
       note="गुजरात जायंट्स के लगातार दो उपविजेता सीज़नों के अहम रेडर।"),
    _p("sonu-jaglan", "Sonu Jaglan", "सोनू जागलान", "raider",
       ["gujarat-giants", "jaipur-pink-panthers"], raid=150, tackle=8, super10=3, seasons="5–7", matches=48,
       note="गुजरात और जयपुर के लिए खेलने वाले रेडर।"),
    _p("ruturaj-koravi", "Ruturaj Koravi", "रुतुराज कोरवी", "defender",
       ["gujarat-giants", "jaipur-pink-panthers"], tackle=130, high5=6, seasons="8–11", matches=65,
       note="गुजरात जायंट्स के कोने के डिफेंडर।"),
    _p("sourav-gulia", "Sourav Gulia", "सौरव गुलिया", "defender",
       ["gujarat-giants"], tackle=100, high5=4, seasons="10–11", matches=38,
       note="गुजरात जायंट्स के युवा कवर डिफेंडर।"),
    _p("rajnish-gg", "Rajnish", "रजनीश", "raider",
       ["gujarat-giants"], raid=120, tackle=8, super10=1, seasons="10–11", matches=35,
       note="गुजरात जायंट्स के युवा रेडर।"),

    # ---- all-rounders & utility ----
    _p("nitin-rawal", "Nitin Rawal", "नितिन रावल", "allrounder",
       ["bengal-warriors", "telugu-titans"], raid=150, tackle=120, super10=2, high5=3, seasons="5–9", matches=80,
       note="रेडिंग और रक्षा दोनों में योगदान देने वाले ऑल-राउंडर।"),

    # ---- international ----
    _p("mohsen-maghsoudlou", "Mohsen Maghsoudlou", "मोहसेन मगसूदलू", "allrounder",
       ["telugu-titans"], raid=115, tackle=55, super10=0, seasons="8–11", matches=75, nat="ईरान",
       note="ईरान के बहुमुखी ऑल-राउंडर; 2018 एशियाई खेलों में स्वर्ण विजेता दल का हिस्सा।"),
    _p("reza-mirbagheri", "Reza Mirbagheri", "रज़ा मीरबाघेरी", "defender",
       ["jaipur-pink-panthers"], raid=28, tackle=172, high5=7, seasons="9–12", matches=80, nat="ईरान",
       note="जयपुर पिंक पैंथर्स के ईरानी लेफ़्ट कवर डिफेंडर; 2023 एशियाई खेलों में ईरान के रजत पदक दल का हिस्सा।"),
    _p("victor-obiero", "Victor Obiero", "विक्टर ओबेरो", "allrounder",
       ["tamil-thalaivas", "puneri-paltan"], raid=18, tackle=8, super10=0, seasons="6–9", matches=18, nat="केन्या",
       note="केन्या राष्ट्रीय टीम के कप्तान और ऑल-राउंडर; पीकेएल में खेलने वाले अग्रणी अफ़्रीकी खिलाड़ियों में।"),
    _p("david-mosambayi", "David Mosambayi", "डेविड मोसाम्बायी", "raider",
       ["puneri-paltan", "haryana-steelers", "jaipur-pink-panthers"], raid=90, tackle=10, super10=1,
       seasons="3–6", matches=35, nat="केन्या",
       note="केन्या के कप्तान और रेडर; 2016 कबड्डी विश्व कप के स्टार और पीकेएल में अग्रणी अफ़्रीकी खिलाड़ियों में से एक।"),

    # ---- more international ----
    _p("mohammadreza-chiyaneh", "Mohammadreza Chiyaneh", "मोहम्मदरेज़ा चियानेह", "defender",
       ["puneri-paltan", "haryana-steelers"], raid=10, tackle=270, high5=8, seasons="9–11", matches=68, nat="ईरान",
       note="ईरान के एलीट कवर डिफेंडर; पीकेएल के सबसे महँगे विदेशी खिलाड़ी रहे और दो बार सर्वश्रेष्ठ डिफेंडर।"),
    _p("milad-jabbari", "Milad Jabbari", "मिलाद जब्बारी", "defender",
       ["telugu-titans", "gujarat-giants"], raid=5, tackle=40, high5=1, seasons="10–11", matches=30, nat="ईरान",
       note="ईरान के राइट कवर डिफेंडर; एशियाई खेल और एशियाई चैंपियनशिप के रजत पदक विजेता।"),
    _p("abolfazl-maghsoudlou", "Abolfazl Maghsoudlou", "अबोल्फ़ज़ल मगसूदलू", "raider",
       ["u-mumba", "patna-pirates", "dabang-delhi", "bengaluru-bulls"], raid=150, tackle=5, super10=2,
       seasons="3–8", matches=50, nat="ईरान",
       note="ईरान के लंबे कद के रेडर; 2018 एशियाई खेलों में स्वर्ण विजेता दल का हिस्सा।"),
    _p("hamid-mirzaei-nader", "Hamid Mirzaei Nader", "हामिद मिर्ज़ाई नादर", "defender",
       ["telugu-titans", "patna-pirates"], raid=5, tackle=16, high5=0, seasons="9–11", matches=24, nat="ईरान",
       note="ईरान के डिफेंडर; 2018 एशियाई खेलों के स्वर्ण और 2022 के रजत पदक विजेता।"),
    _p("young-chang-ko", "Young Chang Ko", "यंग चांग को", "defender",
       ["bengal-warriors", "jaipur-pink-panthers", "u-mumba"], raid=0, tackle=26, high5=1, seasons="5–7", matches=40,
       nat="दक्षिण कोरिया",
       note="दक्षिण कोरिया के कवर डिफेंडर; 2016 विश्व कप में भारत को हराने वाली कोरियाई टीम और 2018 एशियाई खेलों के रजत दल का हिस्सा।"),
    _p("ziaur-rahman", "Ziaur Rahman", "ज़ियाउर रहमान", "defender",
       ["puneri-paltan", "bengal-warriors", "bengaluru-bulls"], raid=2, tackle=30, high5=1, seasons="5–8", matches=30,
       nat="बांग्लादेश",
       note="पीकेएल इतिहास के सबसे प्रभावी बांग्लादेशी खिलाड़ी; 2006 एशियाई खेलों के कांस्य पदक विजेता।"),
    _p("simon-kibura", "Simon Kibura", "साइमन किबुरा", "raider",
       ["puneri-paltan", "bengal-warriors"], raid=2, tackle=0, super10=0, seasons="2–3", matches=4, nat="केन्या",
       note="पीकेएल में खेलने वाले पहले केन्याई खिलाड़ी।"),
    _p("james-kamweti", "James Kamweti", "जेम्स कामवेती", "raider",
       ["up-yoddhas"], raid=8, tackle=1, super10=0, seasons="8–9", matches=6, nat="केन्या",
       note="यूपी योद्धा द्वारा अनुबंधित पहले अफ़्रीकी मूल के खिलाड़ी।"),
]

PLAYER_BY_ID = {p["id"]: p for p in PLAYERS}

# ============================================================ RECORDS =========
# label_hi -> list of (player_id_or_name, value, context_hi)
RECORDS = {
    "career_raid": ("सर्वाधिक रेड अंक (करियर)", [
        ("pardeep-narwal", 1801, "सीज़न 2–11"),
        ("maninder-singh", 1528, "सीज़न 1, 5–11"),
        ("pawan-sehrawat", 1460, "सीज़न 5–12"),
        ("arjun-deshwal", 1381, "सीज़न 6–12"),
        ("naveen-kumar", 1240, "सीज़न 6–12"),
        ("rahul-chaudhari", 1100, "सीज़न 1–9"),
        ("ashu-malik", 1085, "सीज़न 8–12"),
        ("sachin-tanwar", 1034, "सीज़न 5–11"),
        ("devank-dalal", 849, "सीज़न 9–12"),
        ("vikash-kandola", 813, "सीज़न 6–11"),
    ]),
    "career_tackle": ("सर्वाधिक टैकल अंक (करियर)", [
        ("fazel-atrachali", 649, "सीज़न 2–12"),
        ("nitesh-kumar", 465, "सीज़न 5–12"),
        ("surjeet-singh", 415, "सीज़न 1–11"),
        ("manjeet-chhillar", 391, "सीज़न 1–8"),
        ("sunil-kumar", 390, "सीज़न 5–12"),
        ("mohammadreza-shadloui", 370, "सीज़न 8–12"),
        ("girish-ernak", 362, "सीज़न 1–9"),
        ("ravinder-pahal", 339, "सीज़न 1–11"),
        ("sandeep-narwal", 328, "सीज़न 1–10"),
        ("vishal-bhardwaj", 321, "सीज़न 3–11"),
    ]),
    "career_super10": ("सर्वाधिक सुपर 10 (करियर)", [
        ("pardeep-narwal", 88, "रिकॉर्ड"),
        ("maninder-singh", 78, ""),
        ("pawan-sehrawat", 73, ""),
        ("naveen-kumar", 70, ""),
        ("arjun-deshwal", 55, ""),
        ("ashu-malik", 52, ""),
        ("rahul-chaudhari", 47, ""),
        ("devank-dalal", 40, ""),
        ("sachin-tanwar", 35, ""),
        ("siddharth-desai", 34, ""),
    ]),
    "career_high5": ("सर्वाधिक हाई 5 (करियर)", [
        ("surjeet-singh", 34, "रिकॉर्ड"),
        ("fazel-atrachali", 32, ""),
        ("nitesh-kumar", 31, ""),
        ("manjeet-chhillar", 25, ""),
        ("girish-ernak", 24, ""),
        ("sunil-kumar", 24, ""),
        ("vishal-bhardwaj", 23, ""),
        ("ravinder-pahal", 23, ""),
        ("surender-nada", 20, ""),
        ("sombir", 15, ""),
    ]),
}

# milestone-style single records: (label_hi, holder_hi, value_hi, detail_hi)
RECORD_MILESTONES = [
    ("एक मैच में सर्वाधिक रेड अंक", "पवन सहरावत", "39 अंक",
     "बेंगलुरु बुल्स बनाम हरियाणा स्टीलर्स (सीज़न 7) — टीम के सभी रेड अंक अकेले बनाए।"),
    ("एक सीज़न में सर्वाधिक रेड अंक", "प्रदीप नरवाल", "369 अंक",
     "सीज़न 5 में 26 मैचों में — आज भी अटूट रिकॉर्ड (पवन सहरावत 346 के साथ निकटतम)।"),
    ("एक मैच में सर्वाधिक टैकल अंक", "मोहम्मदरेज़ा चियानेह (शादलोई)", "16 अंक",
     "पटना पाइरेट्स बनाम दबंग दिल्ली (सीज़न 9) — जिसमें 8 सुपर टैकल शामिल।"),
    ("सर्वाधिक रेड अंक (करियर)", "प्रदीप नरवाल", "1801 अंक",
     "1800 रेड अंक पार करने वाले पहले और एकमात्र खिलाड़ी।"),
    ("सर्वाधिक टैकल अंक (करियर)", "फ़ज़ेल अत्राचली", "649 अंक",
     "500 और 600 टैकल अंक तक पहुँचने वाले पहले खिलाड़ी; सीज़न 12 में दबंग दिल्ली के चैंपियन कप्तान और एमवीपी।"),
    ("सर्वाधिक सुपर 10 (करियर)", "प्रदीप नरवाल", "88",
     "मनिंदर सिंह (78) से 10 अधिक।"),
    ("लगातार सर्वाधिक सुपर 10", "नवीन कुमार", "28",
     "जुलाई 2019 से जनवरी 2022 तक लगातार 28 मैचों में सुपर 10।"),
    ("एक मैच में सर्वाधिक टीम स्कोर", "तमिल थलाइवाज़", "74 अंक",
     "बंगाल वॉरियर्स पर 74–37 की जीत (सीज़न 10), जिसमें 6 ऑल-आउट।"),
    ("सर्वाधिक ख़िताब (टीम)", "पटना पाइरेट्स", "3 ख़िताब",
     "लगातार सीज़न 3, 4 और 5 जीतकर हैट्रिक।"),
    ("सबसे लंबा विजय क्रम", "यू मुंबा", "11 मैच",
     "सीज़न 3 में लगातार 11 जीत।"),
]

# ============================================================ INTERNATIONAL ===
WORLD_CUP = [
    ("2004", "मुंबई, भारत", "भारत", "ईरान", "55–27"),
    ("2007", "पनवेल, भारत", "भारत", "ईरान", "29–19"),
    ("2016", "अहमदाबाद, भारत", "भारत", "ईरान", "38–29"),
]

ASIAN_GAMES_MEN = [
    ("1990", "भारत"), ("1994", "भारत"), ("1998", "भारत"), ("2002", "भारत"),
    ("2006", "भारत"), ("2010", "भारत"), ("2014", "भारत"), ("2018", "ईरान"),
    ("2022", "भारत"),
]
ASIAN_GAMES_WOMEN = [
    ("2010", "भारत", "थाईलैंड", "28–14"),
    ("2014", "भारत", "ईरान", "31–21"),
    ("2018", "ईरान", "भारत", "27–24"),
    ("2022", "भारत", "चीनी ताइपे", "26–25"),
]

# ============================================================ MATCHES =========
# Match results by PKL season. Representative coverage: opening match, a
# selection of league-stage games, and the full playoff bracket (eliminators,
# semifinals, final). Scores are champion-/winner-side from public reporting and
# are approximate for some league games. Finals align with the SEASONS table.
# Each match: stage_hi, date (ISO), team a/b slugs, scores sa/sb, venue_hi.
def _m(stage, date, a, b, sa, sb, venue):
    return dict(stage=stage, date=date, a=a, b=b, sa=sa, sb=sb, venue=venue)


# common venue shorthands (Hindi)
_V = {
    "mum_svp": "सरदार वल्लभभाई पटेल इंडोर स्टेडियम, मुंबई",
    "mum_nsci": "एनएससीआई डोम, मुंबई",
    "del_tyag": "त्यागराज स्पोर्ट्स कॉम्प्लेक्स, नई दिल्ली",
    "hyd_gachi": "गाचीबोवली इंडोर स्टेडियम, हैदराबाद",
    "che_jln": "जवाहरलाल नेहरू इंडोर स्टेडियम, चेन्नई",
    "ben_kanteerava": "श्री कांतीरवा इंडोर स्टेडियम, बेंगलुरु",
    "kol_netaji": "नेताजी इंडोर स्टेडियम, कोलकाता",
    "pun_balewadi": "शिव छत्रपति स्पोर्ट्स कॉम्प्लेक्स, बालेवाड़ी, पुणे",
    "ahm_eka": "ईकेए एरिना (ट्रांसस्टेडिया), अहमदाबाद",
    "jai_sms": "सवाई मानसिंह इंडोर स्टेडियम, जयपुर",
    "luc_bbd": "बीबीडी अकादमी, लखनऊ",
    "vizag": "राजीव गांधी इंडोर स्टेडियम, विशाखापत्तनम",
    "hyd_gmc": "जीएमसी बालयोगी स्टेडियम, गचीबोवली, हैदराबाद",
    "ben_sheraton": "शेरेटन ग्रैंड (बायो-बबल), बेंगलुरु",
    "pat_pataliputra": "पाटलिपुत्र खेल परिसर, पटना",
    "del_thyagaraj": "त्यागराज स्पोर्ट्स कॉम्प्लेक्स, नई दिल्ली",
    "del_thyagaraj_indoor": "त्यागराज इंडोर स्टेडियम, नई दिल्ली",
    "che_sdat": "एसडीएटी मल्टीपर्पस इंडोर स्टेडियम, चेन्नई",
}

MATCHES = {
    1: [
        _m("उद्घाटन मैच", "2014-07-26", "u-mumba", "jaipur-pink-panthers", 33, 29, _V["mum_svp"]),
        _m("लीग चरण", "2014-08-02", "telugu-titans", "bengal-warriors", 41, 32, _V["hyd_gachi"]),
        _m("लीग चरण", "2014-08-09", "patna-pirates", "dabang-delhi", 38, 33, _V["del_tyag"]),
        _m("लीग चरण", "2014-08-16", "u-mumba", "bengaluru-bulls", 36, 27, _V["ben_kanteerava"]),
        _m("लीग चरण", "2014-08-21", "jaipur-pink-panthers", "telugu-titans", 34, 28, _V["jai_sms"]),
        _m("सेमीफ़ाइनल 1", "2014-08-30", "jaipur-pink-panthers", "telugu-titans", 39, 34, _V["mum_svp"]),
        _m("सेमीफ़ाइनल 2", "2014-08-30", "u-mumba", "bengal-warriors", 33, 28, _V["mum_svp"]),
        _m("फ़ाइनल", "2014-08-31", "jaipur-pink-panthers", "u-mumba", 35, 24, _V["mum_svp"]),
    ],
    2: [
        _m("उद्घाटन मैच", "2015-07-18", "u-mumba", "telugu-titans", 38, 30, _V["mum_nsci"]),
        _m("लीग चरण", "2015-07-25", "dabang-delhi", "patna-pirates", 35, 31, _V["del_tyag"]),
        _m("लीग चरण", "2015-08-01", "bengaluru-bulls", "jaipur-pink-panthers", 34, 29, _V["ben_kanteerava"]),
        _m("लीग चरण", "2015-08-08", "u-mumba", "bengal-warriors", 40, 25, _V["kol_netaji"]),
        _m("लीग चरण", "2015-08-15", "telugu-titans", "bengaluru-bulls", 33, 33, _V["hyd_gachi"]),
        _m("सेमीफ़ाइनल 1", "2015-08-22", "u-mumba", "telugu-titans", 30, 22, _V["mum_nsci"]),
        _m("सेमीफ़ाइनल 2", "2015-08-22", "bengaluru-bulls", "dabang-delhi", 34, 28, _V["mum_nsci"]),
        _m("फ़ाइनल", "2015-08-23", "u-mumba", "bengaluru-bulls", 36, 30, _V["mum_nsci"]),
    ],
    3: [
        _m("उद्घाटन मैच", "2016-01-30", "u-mumba", "telugu-titans", 35, 26, _V["mum_nsci"]),
        _m("लीग चरण", "2016-02-06", "patna-pirates", "bengaluru-bulls", 39, 30, _V["pat_pataliputra"]),
        _m("लीग चरण", "2016-02-13", "u-mumba", "dabang-delhi", 42, 24, _V["mum_nsci"]),
        _m("लीग चरण", "2016-02-20", "telugu-titans", "jaipur-pink-panthers", 36, 31, _V["hyd_gachi"]),
        _m("लीग चरण", "2016-03-01", "patna-pirates", "u-mumba", 33, 30, _V["del_tyag"]),
        _m("सेमीफ़ाइनल 1", "2016-03-04", "patna-pirates", "telugu-titans", 33, 30, _V["del_tyag"]),
        _m("सेमीफ़ाइनल 2", "2016-03-04", "u-mumba", "dabang-delhi", 31, 25, _V["del_tyag"]),
        _m("फ़ाइनल", "2016-03-05", "patna-pirates", "u-mumba", 31, 28, _V["del_tyag"]),
    ],
    4: [
        _m("उद्घाटन मैच", "2016-06-25", "patna-pirates", "telugu-titans", 41, 33, _V["hyd_gachi"]),
        _m("लीग चरण", "2016-07-02", "jaipur-pink-panthers", "u-mumba", 35, 30, _V["jai_sms"]),
        _m("लीग चरण", "2016-07-09", "patna-pirates", "dabang-delhi", 44, 28, _V["del_tyag"]),
        _m("लीग चरण", "2016-07-16", "telugu-titans", "bengaluru-bulls", 38, 34, _V["hyd_gachi"]),
        _m("लीग चरण", "2016-07-23", "jaipur-pink-panthers", "bengal-warriors", 37, 26, _V["kol_netaji"]),
        _m("एलिमिनेटर", "2016-07-29", "jaipur-pink-panthers", "telugu-titans", 35, 31, _V["hyd_gachi"]),
        _m("सेमीफ़ाइनल 1", "2016-07-30", "patna-pirates", "u-mumba", 36, 24, _V["hyd_gachi"]),
        _m("सेमीफ़ाइनल 2", "2016-07-30", "jaipur-pink-panthers", "dabang-delhi", 34, 30, _V["hyd_gachi"]),
        _m("फ़ाइनल", "2016-07-31", "patna-pirates", "jaipur-pink-panthers", 37, 29, _V["hyd_gachi"]),
    ],
    5: [
        _m("उद्घाटन मैच", "2017-07-28", "u-mumba", "bengal-warriors", 35, 28, _V["hyd_gachi"]),
        _m("लीग चरण", "2017-08-05", "patna-pirates", "tamil-thalaivas", 48, 24, _V["che_jln"]),
        _m("लीग चरण", "2017-08-12", "gujarat-giants", "telugu-titans", 38, 30, _V["ahm_eka"]),
        _m("लीग चरण", "2017-09-02", "patna-pirates", "up-yoddhas", 51, 28, _V["luc_bbd"]),
        _m("लीग चरण", "2017-09-20", "bengal-warriors", "gujarat-giants", 32, 31, _V["kol_netaji"]),
        _m("एलिमिनेटर 1", "2017-10-24", "gujarat-giants", "bengaluru-bulls", 38, 33, _V["che_jln"]),
        _m("एलिमिनेटर 2", "2017-10-24", "patna-pirates", "telugu-titans", 39, 34, _V["che_jln"]),
        _m("सेमीफ़ाइनल 1", "2017-10-26", "gujarat-giants", "bengal-warriors", 33, 30, _V["che_jln"]),
        _m("सेमीफ़ाइनल 2", "2017-10-26", "patna-pirates", "u-mumba", 42, 38, _V["che_jln"]),
        _m("फ़ाइनल", "2017-10-28", "patna-pirates", "gujarat-giants", 55, 38, _V["che_jln"]),
    ],
    6: [
        _m("उद्घाटन मैच", "2018-10-07", "tamil-thalaivas", "bengal-warriors", 39, 30, _V["che_jln"]),
        _m("लीग चरण", "2018-10-20", "bengaluru-bulls", "u-mumba", 44, 33, _V["ben_kanteerava"]),
        _m("लीग चरण", "2018-11-03", "gujarat-giants", "patna-pirates", 41, 38, _V["ahm_eka"]),
        _m("लीग चरण", "2018-11-24", "bengaluru-bulls", "dabang-delhi", 39, 29, _V["ben_kanteerava"]),
        _m("लीग चरण", "2018-12-15", "gujarat-giants", "u-mumba", 34, 28, _V["ahm_eka"]),
        _m("एलिमिनेटर 1", "2018-12-29", "u-mumba", "tamil-thalaivas", 37, 31, _V["mum_nsci"]),
        _m("एलिमिनेटर 2", "2018-12-29", "dabang-delhi", "telugu-titans", 36, 30, _V["mum_nsci"]),
        _m("सेमीफ़ाइनल 1", "2019-01-03", "gujarat-giants", "dabang-delhi", 39, 31, _V["mum_nsci"]),
        _m("सेमीफ़ाइनल 2", "2019-01-03", "bengaluru-bulls", "u-mumba", 36, 28, _V["mum_nsci"]),
        _m("फ़ाइनल", "2019-01-05", "bengaluru-bulls", "gujarat-giants", 38, 33, _V["mum_nsci"]),
    ],
    7: [
        _m("उद्घाटन मैच", "2019-07-20", "telugu-titans", "tamil-thalaivas", 34, 30, _V["hyd_gachi"]),
        _m("लीग चरण", "2019-08-03", "bengaluru-bulls", "haryana-steelers", 54, 38, _V["ben_kanteerava"]),
        _m("लीग चरण", "2019-08-24", "bengal-warriors", "patna-pirates", 40, 32, _V["kol_netaji"]),
        _m("लीग चरण", "2019-09-14", "dabang-delhi", "u-mumba", 35, 29, _V["del_tyag"]),
        _m("लीग चरण", "2019-10-05", "bengal-warriors", "dabang-delhi", 36, 34, _V["kol_netaji"]),
        _m("एलिमिनेटर 1", "2019-10-14", "u-mumba", "haryana-steelers", 39, 33, _V["ahm_eka"]),
        _m("एलिमिनेटर 2", "2019-10-14", "dabang-delhi", "bengaluru-bulls", 38, 33, _V["ahm_eka"]),
        _m("सेमीफ़ाइनल 1", "2019-10-16", "bengal-warriors", "u-mumba", 37, 28, _V["ahm_eka"]),
        _m("सेमीफ़ाइनल 2", "2019-10-16", "dabang-delhi", "haryana-steelers", 43, 39, _V["ahm_eka"]),
        _m("फ़ाइनल", "2019-10-19", "bengal-warriors", "dabang-delhi", 39, 34, _V["ahm_eka"]),
    ],
    8: [
        _m("उद्घाटन मैच", "2021-12-22", "u-mumba", "bengaluru-bulls", 36, 30, _V["ben_sheraton"]),
        _m("लीग चरण", "2022-01-05", "dabang-delhi", "patna-pirates", 41, 35, _V["ben_sheraton"]),
        _m("लीग चरण", "2022-01-20", "puneri-paltan", "u-mumba", 38, 33, _V["ben_sheraton"]),
        _m("लीग चरण", "2022-02-01", "patna-pirates", "bengaluru-bulls", 45, 40, _V["ben_sheraton"]),
        _m("लीग चरण", "2022-02-10", "dabang-delhi", "bengal-warriors", 37, 32, _V["ben_sheraton"]),
        _m("एलिमिनेटर 1", "2022-02-19", "patna-pirates", "u-mumba", 35, 29, _V["ben_sheraton"]),
        _m("एलिमिनेटर 2", "2022-02-19", "puneri-paltan", "bengaluru-bulls", 38, 35, _V["ben_sheraton"]),
        _m("सेमीफ़ाइनल 1", "2022-02-23", "dabang-delhi", "puneri-paltan", 42, 31, _V["ben_sheraton"]),
        _m("सेमीफ़ाइनल 2", "2022-02-23", "patna-pirates", "u-mumba", 39, 32, _V["ben_sheraton"]),
        _m("फ़ाइनल", "2022-02-25", "dabang-delhi", "patna-pirates", 37, 36, _V["ben_sheraton"]),
    ],
    9: [
        _m("उद्घाटन मैच", "2022-10-07", "bengaluru-bulls", "tamil-thalaivas", 36, 32, _V["ben_kanteerava"]),
        _m("लीग चरण", "2022-10-22", "jaipur-pink-panthers", "patna-pirates", 41, 34, _V["jai_sms"]),
        _m("लीग चरण", "2022-11-12", "puneri-paltan", "u-mumba", 39, 30, _V["pun_balewadi"]),
        _m("लीग चरण", "2022-11-26", "jaipur-pink-panthers", "dabang-delhi", 37, 33, _V["hyd_gmc"]),
        _m("लीग चरण", "2022-12-03", "puneri-paltan", "bengaluru-bulls", 35, 29, _V["mum_nsci"]),
        _m("एलिमिनेटर 1", "2022-12-12", "jaipur-pink-panthers", "u-mumba", 38, 34, _V["mum_nsci"]),
        _m("एलिमिनेटर 2", "2022-12-12", "dabang-delhi", "bengaluru-bulls", 35, 30, _V["mum_nsci"]),
        _m("सेमीफ़ाइनल 1", "2022-12-15", "puneri-paltan", "dabang-delhi", 40, 32, _V["mum_nsci"]),
        _m("सेमीफ़ाइनल 2", "2022-12-15", "jaipur-pink-panthers", "u-mumba", 41, 30, _V["mum_nsci"]),
        _m("फ़ाइनल", "2022-12-17", "jaipur-pink-panthers", "puneri-paltan", 33, 29, _V["mum_nsci"]),
    ],
    10: [
        _m("उद्घाटन मैच", "2023-12-02", "puneri-paltan", "telugu-titans", 45, 30, _V["hyd_gmc"]),
        _m("लीग चरण", "2023-12-16", "haryana-steelers", "dabang-delhi", 39, 34, _V["hyd_gmc"]),
        _m("लीग चरण", "2024-01-10", "tamil-thalaivas", "bengal-warriors", 74, 37, _V["che_jln"]),
        _m("लीग चरण", "2024-01-25", "puneri-paltan", "haryana-steelers", 36, 31, _V["pun_balewadi"]),
        _m("लीग चरण", "2024-02-05", "dabang-delhi", "jaipur-pink-panthers", 38, 33, _V["del_thyagaraj"]),
        _m("एलिमिनेटर 1", "2024-02-23", "haryana-steelers", "bengal-warriors", 35, 29, _V["hyd_gmc"]),
        _m("एलिमिनेटर 2", "2024-02-23", "dabang-delhi", "u-mumba", 37, 31, _V["hyd_gmc"]),
        _m("सेमीफ़ाइनल 1", "2024-02-28", "puneri-paltan", "dabang-delhi", 33, 28, _V["hyd_gmc"]),
        _m("सेमीफ़ाइनल 2", "2024-02-28", "haryana-steelers", "patna-pirates", 32, 30, _V["hyd_gmc"]),
        _m("फ़ाइनल", "2024-03-01", "puneri-paltan", "haryana-steelers", 28, 25, _V["hyd_gmc"]),
    ],
    11: [
        _m("उद्घाटन मैच", "2024-10-18", "patna-pirates", "jaipur-pink-panthers", 40, 36, _V["vizag"]),
        _m("लीग चरण", "2024-11-01", "haryana-steelers", "bengaluru-bulls", 38, 30, _V["vizag"]),
        _m("लीग चरण", "2024-11-20", "patna-pirates", "dabang-delhi", 42, 35, _V["pun_balewadi"]),
        _m("लीग चरण", "2024-12-10", "haryana-steelers", "telugu-titans", 41, 28, _V["hyd_gmc"]),
        _m("लीग चरण", "2024-12-20", "patna-pirates", "u-mumba", 37, 33, _V["del_thyagaraj"]),
        _m("एलिमिनेटर 1", "2024-12-28", "patna-pirates", "dabang-delhi", 36, 31, _V["pun_balewadi"]),
        _m("एलिमिनेटर 2", "2024-12-28", "jaipur-pink-panthers", "bengaluru-bulls", 35, 30, _V["pun_balewadi"]),
        _m("सेमीफ़ाइनल 1", "2024-12-30", "haryana-steelers", "jaipur-pink-panthers", 33, 29, _V["pun_balewadi"]),
        _m("सेमीफ़ाइनल 2", "2024-12-30", "patna-pirates", "dabang-delhi", 34, 30, _V["pun_balewadi"]),
        _m("फ़ाइनल", "2025-01-01", "haryana-steelers", "patna-pirates", 32, 23, _V["pun_balewadi"]),
    ],
    12: [
        _m("उद्घाटन मैच", "2025-08-29", "tamil-thalaivas", "telugu-titans", 38, 35, _V["vizag"]),
        _m("लीग चरण", "2025-08-31", "bengal-warriors", "haryana-steelers", 54, 44, _V["vizag"]),
        _m("लीग चरण", "2025-09-05", "u-mumba", "bengaluru-bulls", 48, 28, _V["vizag"]),
        _m("लीग चरण", "2025-09-08", "patna-pirates", "puneri-paltan", 48, 37, _V["vizag"]),
        _m("लीग चरण", "2025-09-18", "dabang-delhi", "gujarat-giants", 41, 33, _V["jai_sms"]),
        _m("लीग चरण", "2025-10-05", "puneri-paltan", "telugu-titans", 39, 34, _V["che_sdat"]),
        _m("प्ले-इन 1", "2025-10-24", "jaipur-pink-panthers", "haryana-steelers", 30, 27, _V["del_thyagaraj_indoor"]),
        _m("प्ले-इन 2", "2025-10-24", "patna-pirates", "u-mumba", 40, 31, _V["del_thyagaraj_indoor"]),
        _m("एलिमिनेटर 1", "2025-10-25", "patna-pirates", "jaipur-pink-panthers", 48, 32, _V["del_thyagaraj_indoor"]),
        _m("एलिमिनेटर 2", "2025-10-25", "telugu-titans", "bengaluru-bulls", 37, 32, _V["del_thyagaraj_indoor"]),
        _m("क्वालिफ़ायर 1 (टाई-ब्रेकर)", "2025-10-26", "dabang-delhi", "puneri-paltan", 40, 38, _V["del_thyagaraj_indoor"]),
        _m("एलिमिनेटर 3", "2025-10-28", "telugu-titans", "patna-pirates", 46, 39, _V["del_thyagaraj_indoor"]),
        _m("क्वालिफ़ायर 2", "2025-10-29", "puneri-paltan", "telugu-titans", 50, 45, _V["del_thyagaraj_indoor"]),
        _m("फ़ाइनल", "2025-10-31", "dabang-delhi", "puneri-paltan", 31, 28, _V["del_thyagaraj_indoor"]),
    ],
}

# ============================================================ STANDINGS =======
# Season points tables (final standings). Position 1 = champion, 2 = runner-up
# (aligned with the SEASONS table). Remaining order approximates league-stage
# finish. Seasons 1–4 had 8 teams (14 league games, top 4 to playoffs); seasons
# 5–11 had 12 teams (22 league games, top 6 to playoffs). PKL points: win = 5,
# tie = 3, plus a bonus point for a narrow loss (≤7) or scoring/defensive bonus.
# Mid-table win/loss splits and scores are representative; finals are accurate.
def _st(team, w, l, t, sf, sa, bonus=0, q=False, pts=None):
    # Seasons 1–11 used 5 pts/win, 3 pts/tie, plus bonus points. Season 12
    # switched to a simple 2 pts/win system — pass pts explicitly for that.
    return dict(team=team, p=w + l + t, w=w, l=l, t=t, sf=sf, sa=sa,
                diff=sf - sa, pts=(5 * w + 3 * t + bonus) if pts is None else pts, q=q)


STANDINGS = {
    1: [
        _st("jaipur-pink-panthers", 11, 3, 0, 480, 410, 2, True),
        _st("u-mumba", 10, 4, 0, 470, 420, 2, True),
        _st("telugu-titans", 9, 5, 0, 450, 430, 1, True),
        _st("bengal-warriors", 8, 6, 0, 430, 420, 1, True),
        _st("patna-pirates", 7, 7, 0, 420, 425, 2),
        _st("dabang-delhi", 6, 8, 0, 405, 432, 2),
        _st("bengaluru-bulls", 5, 9, 0, 392, 442, 2),
        _st("puneri-paltan", 4, 10, 0, 380, 450, 2),
    ],
    2: [
        _st("u-mumba", 11, 3, 0, 472, 410, 2, True),
        _st("bengaluru-bulls", 10, 4, 0, 460, 420, 2, True),
        _st("telugu-titans", 9, 4, 1, 450, 425, 0, True),
        _st("dabang-delhi", 8, 6, 0, 432, 422, 2, True),
        _st("patna-pirates", 7, 7, 0, 420, 425, 2),
        _st("jaipur-pink-panthers", 6, 8, 0, 410, 430, 2),
        _st("bengal-warriors", 4, 9, 1, 392, 450, 2),
        _st("puneri-paltan", 4, 10, 0, 380, 455, 1),
    ],
    3: [
        _st("patna-pirates", 11, 3, 0, 482, 420, 2, True),
        _st("u-mumba", 10, 4, 0, 462, 420, 2, True),
        _st("telugu-titans", 9, 5, 0, 446, 430, 1, True),
        _st("dabang-delhi", 8, 6, 0, 432, 426, 1, True),
        _st("bengaluru-bulls", 7, 7, 0, 420, 430, 2),
        _st("jaipur-pink-panthers", 6, 8, 0, 410, 435, 2),
        _st("bengal-warriors", 5, 9, 0, 400, 445, 2),
        _st("puneri-paltan", 4, 10, 0, 386, 452, 2),
    ],
    4: [
        _st("patna-pirates", 11, 3, 0, 492, 430, 2, True),
        _st("jaipur-pink-panthers", 10, 4, 0, 470, 432, 2, True),
        _st("puneri-paltan", 9, 5, 0, 452, 436, 1, True),
        _st("telugu-titans", 8, 6, 0, 440, 432, 1, True),
        _st("u-mumba", 7, 7, 0, 426, 432, 2),
        _st("bengaluru-bulls", 6, 8, 0, 415, 442, 2),
        _st("dabang-delhi", 5, 9, 0, 402, 446, 2),
        _st("bengal-warriors", 4, 10, 0, 390, 455, 2),
    ],
    5: [
        _st("patna-pirates", 18, 4, 0, 852, 750, 3, True),
        _st("gujarat-giants", 17, 5, 0, 830, 760, 3, True),
        _st("bengal-warriors", 15, 7, 0, 800, 770, 3, True),
        _st("bengaluru-bulls", 14, 8, 0, 790, 772, 3, True),
        _st("puneri-paltan", 13, 9, 0, 780, 776, 3, True),
        _st("jaipur-pink-panthers", 12, 10, 0, 770, 780, 3, True),
        _st("u-mumba", 11, 11, 0, 762, 770, 3),
        _st("telugu-titans", 10, 12, 0, 752, 782, 3),
        _st("tamil-thalaivas", 9, 13, 0, 732, 792, 3),
        _st("dabang-delhi", 8, 14, 0, 722, 802, 3),
        _st("up-yoddhas", 7, 15, 0, 715, 808, 3),
        _st("haryana-steelers", 6, 16, 0, 692, 822, 3),
    ],
    6: [
        _st("bengaluru-bulls", 17, 5, 0, 842, 742, 3, True),
        _st("gujarat-giants", 16, 6, 0, 822, 746, 3, True),
        _st("dabang-delhi", 15, 7, 0, 802, 762, 3, True),
        _st("u-mumba", 14, 8, 0, 790, 766, 2, True),
        _st("bengal-warriors", 13, 9, 0, 780, 772, 2, True),
        _st("jaipur-pink-panthers", 11, 11, 0, 762, 776, 3, True),
        _st("telugu-titans", 10, 12, 0, 752, 786, 3),
        _st("patna-pirates", 10, 12, 0, 746, 782, 2),
        _st("haryana-steelers", 9, 13, 0, 736, 796, 3),
        _st("up-yoddhas", 9, 13, 0, 730, 800, 2),
        _st("tamil-thalaivas", 8, 14, 0, 722, 810, 3),
        _st("puneri-paltan", 7, 15, 0, 712, 822, 3),
    ],
    7: [
        _st("bengal-warriors", 16, 6, 0, 832, 752, 3, True),
        _st("dabang-delhi", 15, 7, 0, 816, 756, 3, True),
        _st("u-mumba", 14, 8, 0, 800, 762, 3, True),
        _st("bengaluru-bulls", 13, 9, 0, 790, 766, 3, True),
        _st("haryana-steelers", 12, 10, 0, 776, 770, 3, True),
        _st("jaipur-pink-panthers", 11, 11, 0, 766, 776, 3, True),
        _st("tamil-thalaivas", 10, 12, 0, 756, 782, 3),
        _st("telugu-titans", 9, 13, 0, 746, 792, 3),
        _st("patna-pirates", 9, 13, 0, 740, 796, 2),
        _st("gujarat-giants", 8, 14, 0, 730, 806, 3),
        _st("puneri-paltan", 7, 15, 0, 720, 812, 3),
        _st("up-yoddhas", 6, 16, 0, 706, 826, 3),
    ],
    8: [
        _st("dabang-delhi", 14, 6, 2, 810, 760, 1, True),
        _st("patna-pirates", 14, 7, 1, 806, 766, 0, True),
        _st("puneri-paltan", 13, 8, 1, 796, 770, 2, True),
        _st("u-mumba", 13, 9, 0, 790, 772, 1, True),
        _st("bengaluru-bulls", 12, 10, 0, 780, 776, 1, True),
        _st("bengal-warriors", 11, 11, 0, 770, 782, 1, True),
        _st("tamil-thalaivas", 10, 12, 0, 760, 786, 1),
        _st("gujarat-giants", 9, 13, 0, 750, 796, 2),
        _st("jaipur-pink-panthers", 9, 13, 0, 746, 796, 1),
        _st("haryana-steelers", 8, 14, 0, 736, 806, 1),
        _st("telugu-titans", 7, 15, 0, 722, 816, 1),
        _st("up-yoddhas", 7, 15, 0, 716, 822, 0),
    ],
    9: [
        _st("jaipur-pink-panthers", 16, 6, 0, 835, 750, 3, True),
        _st("puneri-paltan", 15, 7, 0, 822, 756, 3, True),
        _st("dabang-delhi", 14, 8, 0, 802, 766, 3, True),
        _st("bengaluru-bulls", 13, 9, 0, 790, 772, 3, True),
        _st("u-mumba", 12, 10, 0, 776, 776, 3, True),
        _st("haryana-steelers", 11, 11, 0, 766, 782, 3, True),
        _st("patna-pirates", 10, 12, 0, 756, 786, 3),
        _st("tamil-thalaivas", 10, 12, 0, 750, 792, 2),
        _st("gujarat-giants", 9, 13, 0, 742, 802, 3),
        _st("up-yoddhas", 8, 14, 0, 732, 806, 3),
        _st("telugu-titans", 7, 15, 0, 722, 816, 3),
        _st("bengal-warriors", 6, 16, 0, 706, 826, 3),
    ],
    10: [
        _st("puneri-paltan", 18, 4, 0, 862, 730, 3, True),
        _st("haryana-steelers", 15, 7, 0, 816, 756, 3, True),
        _st("dabang-delhi", 14, 8, 0, 802, 762, 3, True),
        _st("patna-pirates", 13, 9, 0, 786, 772, 3, True),
        _st("u-mumba", 12, 10, 0, 776, 776, 3, True),
        _st("jaipur-pink-panthers", 11, 11, 0, 766, 782, 3, True),
        _st("bengaluru-bulls", 10, 12, 0, 756, 786, 3),
        _st("tamil-thalaivas", 10, 12, 0, 750, 792, 2),
        _st("bengal-warriors", 9, 13, 0, 742, 802, 3),
        _st("telugu-titans", 7, 15, 0, 722, 816, 3),
        _st("gujarat-giants", 7, 15, 0, 716, 822, 2),
        _st("up-yoddhas", 6, 16, 0, 706, 826, 3),
    ],
    11: [
        _st("haryana-steelers", 17, 5, 0, 846, 740, 3, True),
        _st("patna-pirates", 16, 6, 0, 830, 752, 3, True),
        _st("jaipur-pink-panthers", 14, 8, 0, 802, 766, 3, True),
        _st("dabang-delhi", 13, 9, 0, 790, 772, 3, True),
        _st("u-mumba", 12, 10, 0, 776, 776, 3, True),
        _st("bengaluru-bulls", 11, 11, 0, 766, 782, 3, True),
        _st("telugu-titans", 11, 11, 0, 760, 782, 2),
        _st("tamil-thalaivas", 10, 12, 0, 750, 792, 3),
        _st("bengal-warriors", 9, 13, 0, 742, 802, 3),
        _st("gujarat-giants", 8, 14, 0, 730, 806, 3),
        _st("puneri-paltan", 7, 15, 0, 722, 816, 3),
        _st("up-yoddhas", 6, 16, 0, 706, 826, 3),
    ],
    # Season 12 (2025): 18 league games per team, 2 pts/win, no ties; top 8 to
    # an expanded play-off. Champion Dabang Delhi and runner-up Puneri Paltan
    # both finished 13–5 (26 pts) — Puneri topped the league on score difference,
    # but the champion is listed first here to match the rest of the dataset.
    12: [
        _st("dabang-delhi", 13, 5, 0, 742, 694, q=True, pts=26),
        _st("puneri-paltan", 13, 5, 0, 748, 702, q=True, pts=26),
        _st("bengaluru-bulls", 11, 7, 0, 724, 706, q=True, pts=22),
        _st("telugu-titans", 10, 8, 0, 730, 712, q=True, pts=20),
        _st("haryana-steelers", 10, 8, 0, 714, 704, q=True, pts=20),
        _st("u-mumba", 10, 8, 0, 710, 706, q=True, pts=20),
        _st("patna-pirates", 8, 10, 0, 772, 760, q=True, pts=16),
        _st("jaipur-pink-panthers", 8, 10, 0, 702, 714, q=True, pts=16),
        _st("up-yoddhas", 7, 11, 0, 690, 720, pts=14),
        _st("tamil-thalaivas", 6, 12, 0, 694, 730, pts=12),
        _st("gujarat-giants", 6, 12, 0, 688, 728, pts=12),
        _st("bengal-warriors", 6, 12, 0, 724, 762, pts=12),
    ],
}


# ============================================================ GLOSSARY ========
# Kabaddi terminology, used on the about / rules content.
GLOSSARY = [
    ("रेड (Raid)", "हमलावर खिलाड़ी (रेडर) विरोधी पाले में जाकर डिफेंडरों को छूकर अंक कमाने का प्रयास करता है।"),
    ("टैकल (Tackle)", "डिफेंडर रेडर को अपने पाले में रोककर उसे लौटने से पहले पकड़ लेते हैं।"),
    ("रेड अंक (Raid Point)", "रेडर द्वारा किसी डिफेंडर को छूकर या बोनस से कमाया गया अंक।"),
    ("टैकल अंक (Tackle Point)", "रेडर को सफलतापूर्वक रोकने पर डिफेंडिंग टीम को मिलने वाला अंक।"),
    ("सुपर रेड (Super Raid)", "एक ही रेड में 3 या अधिक अंक कमाना।"),
    ("सुपर टैकल (Super Tackle)", "जब पाले में 3 या कम डिफेंडर हों और वे रेडर को रोक दें — 1 अतिरिक्त अंक।"),
    ("सुपर 10 (Super 10)", "किसी रेडर द्वारा एक मैच में 10 या अधिक रेड अंक।"),
    ("हाई 5 (High 5)", "किसी डिफेंडर द्वारा एक मैच में 5 या अधिक टैकल अंक।"),
    ("ऑल-आउट (All Out)", "पूरी विरोधी टीम के आउट हो जाने पर 2 अतिरिक्त अंक मिलते हैं।"),
    ("बोनस अंक (Bonus Point)", "जब पाले में 6 या अधिक डिफेंडर हों, रेडर बोनस लाइन पार कर एक अंक कमा सकता है।"),
    ("डू-ऑर-डाई रेड", "लगातार दो ख़ाली रेड के बाद तीसरी रेड में अंक लाना अनिवार्य, वरना रेडर आउट।"),
    ("मैट (Court)", "खेल का मैदान 13×10 मीटर (पुरुष); प्रत्येक टीम में 7 खिलाड़ी मैट पर होते हैं।"),
]


# ============================================================ VENUES ==========
# Major PKL host arenas. seasons = season numbers the venue hosted matches in
# (league legs and/or finals); home = team slugs that use it as a home ground.
# capacity is approximate spectator capacity for kabaddi configuration.
def _v(slug, name, name_hi, city, city_hi, state, capacity, seasons, home,
       opened="", note=""):
    return dict(slug=slug, name=name, name_hi=name_hi, city=city, city_hi=city_hi,
                state=state, capacity=capacity, seasons=seasons, home=home,
                opened=opened, note=note)

VENUES = [
    _v("shree-shiv-chhatrapati-pune", "Shree Shiv Chhatrapati Sports Complex",
       "श्री शिव छत्रपति स्पोर्ट्स कॉम्प्लेक्स", "Pune", "पुणे", "महाराष्ट्र",
       8000, [11], ["puneri-paltan"], opened="1994",
       note="बालेवाड़ी, पुणे स्थित यह विशाल खेल परिसर पुनेरी पलटन का गृह मैदान है। सीज़न 11 के कई मुक़ाबले और फ़ाइनल यहीं खेले गए, जहाँ हरियाणा स्टीलर्स ने पहला ख़िताब जीता। 1994 के राष्ट्रीय खेलों के लिए बना यह परिसर महाराष्ट्र के सबसे बड़े बहुउद्देशीय खेल केंद्रों में से एक है।"),
    _v("thyagaraj-delhi", "Thyagaraj Sports Complex", "त्यागराज स्पोर्ट्स कॉम्प्लेक्स",
       "Delhi", "नई दिल्ली", "दिल्ली", 5600, [3, 8, 12], ["dabang-delhi"], opened="2010",
       note="दबंग दिल्ली के.सी. का गृह मैदान। सीज़न 3 का फ़ाइनल यहीं खेला गया जहाँ पटना पाइरेट्स ने यू मुंबा को हराया। सीज़न 12 के प्लेऑफ़ और फ़ाइनल भी यहीं हुए, जहाँ दबंग दिल्ली ने अपने घरेलू मैदान पर पुनेरी पलटन को 31–28 से हराकर दूसरा ख़िताब जीता। 2010 राष्ट्रमंडल खेलों के लिए बना यह पर्यावरण-अनुकूल स्टेडियम सौर ऊर्जा से संचालित होता है।"),
    _v("gachibowli-hyderabad", "Gachibowli Indoor Stadium", "गाचीबोवली इंडोर स्टेडियम",
       "Hyderabad", "हैदराबाद", "तेलंगाना", 4000, [4, 10], ["telugu-titans"], opened="2002",
       note="तेलुगु टाइटन्स का गृह मैदान। सीज़न 4 का रोमांचक फ़ाइनल यहीं खेला गया जहाँ पटना पाइरेट्स ने जयपुर पिंक पैंथर्स को 37–29 से हराया। 2002 के अफ़्रो-एशियाई खेलों के लिए बना यह इनडोर एरिना।"),
    _v("sardar-vallabhbhai-patel-mumbai", "Sardar Vallabhbhai Patel Indoor Stadium",
       "सरदार वल्लभभाई पटेल इंडोर स्टेडियम", "Mumbai", "मुंबई", "महाराष्ट्र",
       5000, [1], ["u-mumba"], opened="1985",
       note="वर्ली, मुंबई स्थित यह ऐतिहासिक इनडोर स्टेडियम पीकेएल के उद्घाटन सीज़न (सीज़न 1) के फ़ाइनल का गवाह बना, जहाँ जयपुर पिंक पैंथर्स ने यू मुंबा को 35–24 से हराकर पहला ख़िताब जीता।"),
    _v("kanteerava-bangalore", "Sree Kanteerava Indoor Stadium", "श्री कांतीरवा इंडोर स्टेडियम",
       "Bengaluru", "बेंगलुरु", "कर्नाटक", 4000, [2, 5], ["bengaluru-bulls"], opened="1995",
       note="बेंगलुरु बुल्स का गृह मैदान। कई सीज़नों के लीग मुक़ाबले यहाँ खेले गए और यह दक्षिण भारत के सबसे जीवंत कबड्डी केंद्रों में से एक रहा है।"),
    _v("jawaharlal-nehru-chennai", "Jawaharlal Nehru Indoor Stadium",
       "जवाहरलाल नेहरू इंडोर स्टेडियम", "Chennai", "चेन्नई", "तमिलनाडु",
       8000, [5], ["tamil-thalaivas"], opened="1993",
       note="तमिल थलाइवाज़ का गृह मैदान। सीज़न 5 का फ़ाइनल यहीं खेला गया जहाँ पटना पाइरेट्स ने गुजरात को 55–38 से हराया और प्रदीप नरवाल ने 369 रेड अंक का अमर रिकॉर्ड बनाया।"),
    _v("netaji-indoor-kolkata", "Netaji Indoor Stadium", "नेताजी इंडोर स्टेडियम",
       "Kolkata", "कोलकाता", "पश्चिम बंगाल", 12000, [3, 6], ["bengal-warriors"], opened="1975",
       note="बंगाल वॉरियर्स का गृह मैदान। भारत के सबसे बड़े इनडोर स्टेडियमों में से एक, जहाँ पीकेएल के कई यादगार लीग मुक़ाबले खेले गए।"),
    _v("patliputra-patna", "Patliputra Sports Complex", "पाटलिपुत्र स्पोर्ट्स कॉम्प्लेक्स",
       "Patna", "पटना", "बिहार", 4000, [4, 6], ["patna-pirates"], opened="2014",
       note="पटना पाइरेट्स का गृह मैदान। तीन बार के चैंपियन पटना के घरेलू दर्शकों का जोश यहाँ देखते ही बनता है।"),
    _v("rajiv-gandhi-vizag", "Rajiv Gandhi Indoor Stadium", "राजीव गांधी इंडोर स्टेडियम",
       "Visakhapatnam", "विशाखापत्तनम", "आंध्र प्रदेश", 5000, [5, 7, 11, 12], ["telugu-titans"], opened="2009",
       note="विशाखापत्तनम स्थित यह इनडोर एरिना तेलुगु टाइटन्स के घरेलू लेग का हिस्सा रहा है और कई पीकेएल मुक़ाबलों का मेज़बान बना। सीज़न 12 का उद्घाटन चरण भी यहीं खेला गया।"),
    _v("tau-devi-lal-panchkula", "Tau Devi Lal Sports Complex", "ताऊ देवीलाल स्पोर्ट्स कॉम्प्लेक्स",
       "Panchkula", "पंचकूला", "हरियाणा", 4000, [7], ["haryana-steelers"], opened="2008",
       note="हरियाणा स्टीलर्स का गृह मैदान। कबड्डी की धरती हरियाणा में स्थित यह परिसर राज्य के खेल-प्रेमी दर्शकों से भरा रहता है।"),
    _v("eka-arena-ahmedabad", "EKA Arena by TransStadia", "ईकेए एरिना (ट्रांसस्टेडिया)",
       "Ahmedabad", "अहमदाबाद", "गुजरात", 6000, [7], ["gujarat-giants"], opened="2016",
       note="गुजरात जायंट्स का गृह मैदान। सीज़न 7 का फ़ाइनल यहीं खेला गया जहाँ बंगाल वॉरियर्स ने दबंग दिल्ली को 39–34 से हराकर पहला ख़िताब जीता।"),
    _v("dome-nsci-mumbai", "Dome @ NSCI SVP Stadium", "डोम @ एनएससीआई",
       "Mumbai", "मुंबई", "महाराष्ट्र", 5000, [2, 6, 9], ["u-mumba"], opened="2010",
       note="वर्ली, मुंबई स्थित यह आधुनिक इनडोर एरिना कई पीकेएल फ़ाइनल का मेज़बान रहा है — सीज़न 2, सीज़न 6 और सीज़न 9 के ख़िताबी मुक़ाबले यहीं खेले गए।"),
    _v("balewadi-stadium-pune", "Shiv Chhatrapati Badminton Hall", "बालेवाड़ी बैडमिंटन हॉल",
       "Pune", "पुणे", "महाराष्ट्र", 4000, [10], ["puneri-paltan"], opened="2008",
       note="बालेवाड़ी, पुणे के खेल परिसर का हिस्सा; पुनेरी पलटन के सीज़न 10 ख़िताबी अभियान के घरेलू मुक़ाबलों का मेज़बान रहा।"),
]

VENUE_BY_SLUG = {v["slug"]: v for v in VENUES}

# ============================================================ AUCTIONS ========
# पीकेएल खिलाड़ी नीलामी। कीमतें लाख में (1 करोड़ = 100 लाख); ये प्रसिद्ध हेडलाइन
# आँकड़े हैं और अनुमानित हो सकती हैं।
# प्रत्येक buy: slug (खिलाड़ी प्रोफ़ाइल हो तो), name, name_hi, team (टीम slug), lakh.
def _b(slug, name, name_hi, team, lakh):
    return dict(slug=slug, name=name, name_hi=name_hi, team=team, lakh=lakh)


AUCTIONS = {
    1: dict(year="2014", purse_hi="लगभग ₹2.5 करोड़ प्रति टीम",
            note="पीकेएल की पहली खिलाड़ी नीलामी अगस्त 2014 में हुई। उस दौर में कीमतें "
                 "लाखों में थीं — रकेश कुमार सबसे महँगे भारतीय खिलाड़ी रहे।",
            buys=[
                _b("rakesh-kumar", "Rakesh Kumar", "रकेश कुमार", "patna-pirates", 12.80),
                _b("manjeet-chhillar", "Manjeet Chhillar", "मनजीत छिल्लर", "bengaluru-bulls", 12.50),
                _b("anup-kumar", "Anup Kumar", "अनुप कुमार", "u-mumba", 12.00),
                _b("rahul-chaudhari", "Rahul Chaudhari", "राहुल चौधरी", "telugu-titans", 11.00),
                _b("deepak-niwas-hooda", "Deepak Niwas Hooda", "दीपक निवास हुड्डा", "puneri-paltan", 10.50),
                _b("dharmaraj-cheralathan", "Dharmaraj Cheralathan", "धर्मराज चेरालाथन", "u-mumba", 9.00),
            ]),
    2: dict(year="2015", purse_hi="लगभग ₹3 करोड़ प्रति टीम",
            note="सीज़न 2 से पहले अधिकतर टीमों ने अपने मुख्य खिलाड़ी बरकरार रखे; नीलामी "
                 "में कीमतें पहले सीज़न के स्तर के आसपास ही रहीं।",
            buys=[
                _b("kashiling-adake", "Kashiling Adake", "काशीलिंग अडके", "dabang-delhi", 14.00),
                _b("rishank-devadiga", "Rishank Devadiga", "ऋषांक देवडिगा", "u-mumba", 13.00),
                _b("nitin-tomar", "Nitin Tomar", "नितिन तोमर", "puneri-paltan", 12.00),
                _b("shabeer-bapu", "Shabeer Bapu", "शबीर बापू", "telugu-titans", 11.00),
            ]),
    3: dict(year="2016", purse_hi="लगभग ₹3 करोड़ प्रति टीम",
            note="सीज़न 3 (2016) की नीलामी में युवा रेडरों की माँग बढ़ी; प्रदीप नरवाल "
                 "जैसे सितारे उभरने लगे।",
            buys=[
                _b("rohit-kumar", "Rohit Kumar", "रोहित कुमार", "patna-pirates", 20.00),
                _b("pardeep-narwal", "Pardeep Narwal", "प्रदीप नरवाल", "patna-pirates", 18.00),
                _b("rahul-chaudhari", "Rahul Chaudhari", "राहुल चौधरी", "telugu-titans", 16.50),
                _b("ajay-thakur", "Ajay Thakur", "अजय ठाकुर", "puneri-paltan", 15.00),
            ]),
    4: dict(year="2016", purse_hi="लगभग ₹4 करोड़ प्रति टीम",
            note="सीज़न 4 उसी साल (2016) के अंत में खेला गया; अधिकतर दल बरकरार रहे और "
                 "नीलामी सीमित रही।",
            buys=[
                _b("nitin-tomar", "Nitin Tomar", "नितिन तोमर", "puneri-paltan", 23.00),
                _b("pardeep-narwal", "Pardeep Narwal", "प्रदीप नरवाल", "patna-pirates", 22.00),
                _b("rahul-chaudhari", "Rahul Chaudhari", "राहुल चौधरी", "telugu-titans", 20.00),
                _b("manjeet-chhillar", "Manjeet Chhillar", "मनजीत छिल्लर", "puneri-paltan", 18.00),
            ]),
    5: dict(year="2017", purse_hi="₹4 करोड़ वेतन सीमा प्रति टीम",
            note="सीज़न 5 (2017) में लीग 8 से 12 टीमों तक बढ़ी और पर्स बढ़कर ₹4 करोड़ "
                 "हुआ। नितिन तोमर ₹93 लाख में उस समय के सबसे महँगे खिलाड़ी बने।",
            buys=[
                _b("nitin-tomar", "Nitin Tomar", "नितिन तोमर", "up-yoddhas", 93.00),
                _b("rohit-kumar", "Rohit Kumar", "रोहित कुमार", "bengaluru-bulls", 81.00),
                _b("nitin-rawal", "Nitin Rawal", "नितिन रावल", "u-mumba", 36.00),
                _b("rahul-chaudhari", "Rahul Chaudhari", "राहुल चौधरी", "telugu-titans", 35.00),
                _b("surjeet-singh", "Surjeet Singh", "सुरजीत सिंह", "tamil-thalaivas", 33.00),
            ]),
    6: dict(year="2018", purse_hi="₹4 करोड़ वेतन सीमा प्रति टीम",
            note="सीज़न 6 (2018) की नीलामी ऐतिहासिक रही — मोनू गोयत ₹1.51 करोड़ में पीकेएल "
                 "इतिहास के पहले 'करोड़पति' खिलाड़ी बने।",
            buys=[
                _b("monu-goyat", "Monu Goyat", "मोनू गोयत", "haryana-steelers", 151.00),
                _b("nitin-tomar", "Nitin Tomar", "नितिन तोमर", "up-yoddhas", 116.00),
                _b("rohit-kumar", "Rohit Kumar", "रोहित कुमार", "bengaluru-bulls", 83.00),
                _b("deepak-niwas-hooda", "Deepak Niwas Hooda", "दीपक निवास हुड्डा", "jaipur-pink-panthers", 87.00),
                _b("girish-ernak", "Girish Ernak", "गिरीश एर्नाक", "u-mumba", 77.00),
            ]),
    7: dict(year="2019", purse_hi="₹4 करोड़ वेतन सीमा प्रति टीम",
            note="सीज़न 7 (2019) की नीलामी में कई करोड़पति बने। सिद्धार्थ देसाई ₹1.45 करोड़ "
                 "में सबसे महँगे खिलाड़ी रहे।",
            buys=[
                _b("siddharth-desai", "Siddharth Desai", "सिद्धार्थ देसाई", "telugu-titans", 145.00),
                _b("rahul-chaudhari", "Rahul Chaudhari", "राहुल चौधरी", "tamil-thalaivas", 129.00),
                _b("deepak-niwas-hooda", "Deepak Niwas Hooda", "दीपक निवास हुड्डा", "jaipur-pink-panthers", 115.00),
                _b("monu-goyat", "Monu Goyat", "मोनू गोयत", "patna-pirates", 96.00),
                _b("nitin-tomar", "Nitin Tomar", "नितिन तोमर", "up-yoddhas", 77.00),
            ]),
    8: dict(year="2021", purse_hi="₹4 करोड़ वेतन सीमा प्रति टीम",
            note="सीज़न 8 (2021) की नीलामी में प्रदीप नरवाल ₹1.65 करोड़ में बिककर उस समय "
                 "के पीकेएल इतिहास के सबसे महँगे खिलाड़ी बन गए।",
            buys=[
                _b("pardeep-narwal", "Pardeep Narwal", "प्रदीप नरवाल", "up-yoddhas", 165.00),
                _b("siddharth-desai", "Siddharth Desai", "सिद्धार्थ देसाई", "u-mumba", 130.00),
                _b("fazel-atrachali", "Fazel Atrachali", "फ़ज़ल अत्राचली", "u-mumba", 100.00),
                _b("naveen-kumar", "Naveen Kumar", "नवीन कुमार", "dabang-delhi", 98.00),
                _b("sandeep-narwal", "Sandeep Narwal", "संदीप नरवाल", "patna-pirates", 77.00),
            ]),
    9: dict(year="2022", purse_hi="₹5 करोड़ वेतन सीमा प्रति टीम",
            note="सीज़न 9 (2022) की नीलामी में पवन सहरावत ₹2.605 करोड़ में बिककर पीकेएल "
                 "इतिहास के सर्वकालिक सबसे महँगे खिलाड़ी बने।",
            buys=[
                _b("pawan-sehrawat", "Pawan Sehrawat", "पवन सहरावत", "telugu-titans", 260.50),
                _b("maninder-singh", "Maninder Singh", "मनिंदर सिंह", "bengal-warriors", 96.00),
                _b("vikash-kandola", "Vikash Kandola", "विकाश कंडोला", "haryana-steelers", 90.00),
                _b("sachin-tanwar", "Sachin Tanwar", "सचिन तंवर", "gujarat-giants", 88.00),
                _b("surender-gill", "Surender Gill", "सुरेंद्र गिल", "up-yoddhas", 85.00),
                _b("guman-singh", "Guman Singh", "गुमान सिंह", "gujarat-giants", 77.00),
            ]),
    10: dict(year="2023", purse_hi="₹5 करोड़ वेतन सीमा प्रति टीम",
             note="सीज़न 10 (2023) की नीलामी में अधिकतर टीमों ने अपने स्टार बरकरार रखे; "
                  "युवा भारतीय रेडरों पर अच्छी बोलियाँ लगीं।",
             buys=[
                 _b("ashu-malik", "Ashu Malik", "आशु मलिक", "dabang-delhi", 75.00),
                 _b("fazel-atrachali", "Fazel Atrachali", "फ़ज़ल अत्राचली", "gujarat-giants", 72.00),
                 _b("vishal-bhardwaj", "Vishal Bhardwaj", "विशाल भारद्वाज", "telugu-titans", 68.00),
                 _b("sachin-tanwar", "Sachin Tanwar", "सचिन तंवर", "tamil-thalaivas", 65.00),
             ]),
    11: dict(year="2024", purse_hi="₹5 करोड़ वेतन सीमा प्रति टीम",
             note="सीज़न 11 (2024) की नीलामी में मोहम्मदरेज़ा शादलोई ₹2.345 करोड़ में बिककर "
                  "किसी भी सीज़न के सबसे महँगे और सर्वकालिक सबसे महँगे विदेशी खिलाड़ी बने।",
             buys=[
                 _b("mohammadreza-shadloui", "Mohammadreza Shadloui", "मोहम्मदरेज़ा शादलोई", "puneri-paltan", 234.50),
                 _b("devank-dalal", "Devank Dalal", "देवांक दलाल", "patna-pirates", 70.00),
                 _b("aslam-inamdar", "Aslam Inamdar", "अस्लम इनामदार", "puneri-paltan", 70.00),
                 _b("nitesh-kumar", "Nitesh Kumar", "नितेश कुमार", "tamil-thalaivas", 68.00),
                 _b("sunil-kumar", "Sunil Kumar", "सुनील कुमार", "jaipur-pink-panthers", 60.00),
             ]),
    12: dict(year="2025", purse_hi="₹5 करोड़ वेतन सीमा प्रति टीम",
             note="सीज़न 12 (2025) की नीलामी 31 मई–1 जून 2025 को मुंबई में हुई। रिकॉर्ड 10 "
                  "खिलाड़ी ₹1 करोड़ के पार बिके — किसी एक नीलामी में सर्वाधिक। मोहम्मदरेज़ा शादलोई "
                  "₹2.23 करोड़ में सबसे महँगे रहे, जबकि देवांक दलाल ₹2.205 करोड़ में सबसे महँगे "
                  "भारतीय खिलाड़ी बने।",
             buys=[
                 _b("mohammadreza-shadloui", "Mohammadreza Shadloui", "मोहम्मदरेज़ा शादलोई", "gujarat-giants", 223.00),
                 _b("devank-dalal", "Devank Dalal", "देवांक दलाल", "bengal-warriors", 220.50),
                 _b("ashu-malik", "Ashu Malik", "आशु मलिक", "dabang-delhi", 190.00),
                 _b("", "Ankit Jaglan", "अंकित जागलान", "patna-pirates", 157.25),
                 _b("arjun-deshwal", "Arjun Deshwal", "अर्जुन देशवाल", "tamil-thalaivas", 140.50),
                 _b("", "Yogesh Dahiya", "योगेश दहिया", "bengaluru-bulls", 112.50),
             ]),
}

# सर्वकालिक सबसे महँगे पीकेएल खिलाड़ी (नीलामी)। season = जिस सीज़न की नीलामी।
ALL_TIME_EXPENSIVE = [
    dict(season=9,  year="2022", **_b("pawan-sehrawat", "Pawan Sehrawat", "पवन सहरावत", "telugu-titans", 260.50)),
    dict(season=11, year="2024", **_b("mohammadreza-shadloui", "Mohammadreza Shadloui", "मोहम्मदरेज़ा शादलोई", "puneri-paltan", 234.50)),
    dict(season=12, year="2025", **_b("mohammadreza-shadloui", "Mohammadreza Shadloui", "मोहम्मदरेज़ा शादलोई", "gujarat-giants", 223.00)),
    dict(season=12, year="2025", **_b("devank-dalal", "Devank Dalal", "देवांक दलाल", "bengal-warriors", 220.50)),
    dict(season=12, year="2025", **_b("ashu-malik", "Ashu Malik", "आशु मलिक", "dabang-delhi", 190.00)),
    dict(season=8,  year="2021", **_b("pardeep-narwal", "Pardeep Narwal", "प्रदीप नरवाल", "up-yoddhas", 165.00)),
    dict(season=12, year="2025", **_b("", "Ankit Jaglan", "अंकित जागलान", "patna-pirates", 157.25)),
    dict(season=6,  year="2018", **_b("monu-goyat", "Monu Goyat", "मोनू गोयत", "haryana-steelers", 151.00)),
    dict(season=7,  year="2019", **_b("siddharth-desai", "Siddharth Desai", "सिद्धार्थ देसाई", "telugu-titans", 145.00)),
    dict(season=8,  year="2021", **_b("siddharth-desai", "Siddharth Desai", "सिद्धार्थ देसाई", "u-mumba", 130.00)),
    dict(season=7,  year="2019", **_b("rahul-chaudhari", "Rahul Chaudhari", "राहुल चौधरी", "tamil-thalaivas", 129.00)),
    dict(season=6,  year="2018", **_b("nitin-tomar", "Nitin Tomar", "नितिन तोमर", "up-yoddhas", 116.00)),
    dict(season=7,  year="2019", **_b("deepak-niwas-hooda", "Deepak Niwas Hooda", "दीपक निवास हुड्डा", "jaipur-pink-panthers", 115.00)),
    dict(season=8,  year="2021", **_b("fazel-atrachali", "Fazel Atrachali", "फ़ज़ल अत्राचली", "u-mumba", 100.00)),
    dict(season=8,  year="2021", **_b("naveen-kumar", "Naveen Kumar", "नवीन कुमार", "dabang-delhi", 98.00)),
    dict(season=9,  year="2022", **_b("maninder-singh", "Maninder Singh", "मनिंदर सिंह", "bengal-warriors", 96.00)),
    dict(season=7,  year="2019", **_b("monu-goyat", "Monu Goyat", "मोनू गोयत", "patna-pirates", 96.00)),
    dict(season=5,  year="2017", **_b("nitin-tomar", "Nitin Tomar", "नितिन तोमर", "up-yoddhas", 93.00)),
    dict(season=9,  year="2022", **_b("vikash-kandola", "Vikash Kandola", "विकाश कंडोला", "haryana-steelers", 90.00)),
    dict(season=9,  year="2022", **_b("sachin-tanwar", "Sachin Tanwar", "सचिन तंवर", "gujarat-giants", 88.00)),
    dict(season=9,  year="2022", **_b("surender-gill", "Surender Gill", "सुरेंद्र गिल", "up-yoddhas", 85.00)),
    dict(season=6,  year="2018", **_b("rohit-kumar", "Rohit Kumar", "रोहित कुमार", "bengaluru-bulls", 83.00)),
]

# ============================================================ ALL-STAR ========
# पीकेएल ऑल-स्टार / प्रदर्शनी मुक़ाबले। इनमें लीग के शीर्ष सितारों को दो टीमों में
# बाँटकर एक प्रदर्शनी मैच खेला जाता है। ये आँकड़े प्रतिनिधिक हैं और प्रदर्शनी
# प्रारूप के अनुसार संकलित किए गए हैं।
# रोस्टर प्रविष्टि: (खिलाड़ी slug — प्रोफ़ाइल हो तो, name, name_hi, टीम slug, role)
def _ar(slug, name, name_hi, team, role):
    return dict(slug=slug, name=name, name_hi=name_hi, team=team, role=role)


def _ap(slug, name, name_hi, team, line_hi):
    return dict(slug=slug, name=name, name_hi=name_hi, team=team, line_hi=line_hi)


ALL_STAR_GAMES = [
    dict(
        slug="season-5", season=5, year="2017",
        title_hi="पीकेएल सीज़न 5 ऑल-स्टार शोकेस",
        subtitle_hi="उत्तर ज़ोन ऑल-स्टार्स बनाम दक्षिण ज़ोन ऑल-स्टार्स",
        date_hi="अगस्त 2017", venue_hi="चेन्नई", city_hi="चेन्नई, तमिलनाडु",
        format_hi="उत्तर बनाम दक्षिण (ज़ोन प्रारूप)",
        teamA=dict(short="उत्तर", name_hi="उत्तर ज़ोन ऑल-स्टार्स", color="#FF6B00", score=38),
        teamB=dict(short="दक्षिण", name_hi="दक्षिण ज़ोन ऑल-स्टार्स", color="#0EA5E9", score=34),
        winner="A",
        mvp=_ap("pardeep-narwal", "Pardeep Narwal", "प्रदीप नरवाल", "patna-pirates",
                "16 रेड अंक — सुपर रेड और लगातार धावों ने उत्तर को जीत दिलाई"),
        rosterA=[
            _ar("pardeep-narwal", "Pardeep Narwal", "प्रदीप नरवाल", "patna-pirates", "raider"),
            _ar("nitin-tomar", "Nitin Tomar", "नितिन तोमर", "up-yoddhas", "raider"),
            _ar("rohit-kumar", "Rohit Kumar", "रोहित कुमार", "bengaluru-bulls", "raider"),
            _ar("deepak-niwas-hooda", "Deepak Niwas Hooda", "दीपक निवास हुड्डा", "puneri-paltan", "allrounder"),
            _ar("monu-goyat", "Monu Goyat", "मोनू गोयत", "patna-pirates", "raider"),
            _ar("surjeet-singh", "Surjeet Singh", "सुरजीत सिंह", "tamil-thalaivas", "defender"),
            _ar("manjeet-chhillar", "Manjeet Chhillar", "मंजीत छिल्लर", "puneri-paltan", "defender"),
            _ar("ravinder-pahal", "Ravinder Pahal", "रविंदर पहल", "dabang-delhi", "defender"),
        ],
        rosterB=[
            _ar("rahul-chaudhari", "Rahul Chaudhari", "राहुल चौधरी", "telugu-titans", "raider"),
            _ar("ajay-thakur", "Ajay Thakur", "अजय ठाकुर", "tamil-thalaivas", "raider"),
            _ar("anup-kumar", "Anup Kumar", "अनुप कुमार", "u-mumba", "raider"),
            _ar("k-prapanjan", "K. Prapanjan", "के. प्रपंजन", "tamil-thalaivas", "raider"),
            _ar("kashiling-adake", "Kashiling Adake", "कशीलिंग अडके", "dabang-delhi", "raider"),
            _ar("fazel-atrachali", "Fazel Atrachali", "फ़ज़ेल अत्राचली", "u-mumba", "defender"),
            _ar("dharmaraj-cheralathan", "Dharmaraj Cheralathan", "धर्मराज चेरलाथन", "puneri-paltan", "defender"),
            _ar("sandeep-narwal", "Sandeep Narwal", "संदीप नरवाल", "patna-pirates", "allrounder"),
        ],
        performers=[
            _ap("pardeep-narwal", "Pardeep Narwal", "प्रदीप नरवाल", "patna-pirates",
                "16 रेड अंक — मैच के सर्वश्रेष्ठ खिलाड़ी (MVP)"),
            _ap("rahul-chaudhari", "Rahul Chaudhari", "राहुल चौधरी", "telugu-titans",
                "13 रेड अंक — दक्षिण के सबसे सफल रेडर"),
            _ap("fazel-atrachali", "Fazel Atrachali", "फ़ज़ेल अत्राचली", "u-mumba",
                "5 टैकल अंक — मज़बूत रक्षापंक्ति का नेतृत्व"),
            _ap("surjeet-singh", "Surjeet Singh", "सुरजीत सिंह", "tamil-thalaivas",
                "4 टैकल अंक — उत्तर की रक्षा का आधार"),
        ],
        note="सीज़न 5 (2017) में लीग 8 से बढ़कर 12 टीमों की हुई और इस विस्तार के जश्न में "
             "शीर्ष सितारों का यह ऑल-स्टार शोकेस आयोजित किया गया। प्रदीप नरवाल, राहुल चौधरी, "
             "अनुप कुमार और अजय ठाकुर जैसे लीग के सबसे चमकदार नाम दो ज़ोनल टीमों — उत्तर और "
             "दक्षिण — में बँटकर आमने-सामने आए। उत्तर ज़ोन ने प्रदीप नरवाल की धमाकेदार रेडिंग "
             "के दम पर 38–34 से मुक़ाबला जीता। यह प्रदर्शनी मैच कबड्डी प्रशंसकों के लिए अपने "
             "पसंदीदा सितारों को एक ही मैट पर देखने का दुर्लभ मौक़ा रहा।"),
    dict(
        slug="season-6", season=6, year="2018",
        title_hi="पीकेएल सीज़न 6 ऑल-स्टार शोकेस",
        subtitle_hi="भारतीय ऑल-स्टार्स बनाम विश्व ऑल-स्टार्स",
        date_hi="अक्टूबर 2018", venue_hi="मुंबई", city_hi="मुंबई, महाराष्ट्र",
        format_hi="भारत बनाम विश्व (देशीय प्रारूप)",
        teamA=dict(short="भारत", name_hi="भारतीय ऑल-स्टार्स", color="#FF6B00", score=41),
        teamB=dict(short="विश्व", name_hi="विश्व ऑल-स्टार्स", color="#16A34A", score=39),
        winner="A",
        mvp=_ap("nitin-tomar", "Nitin Tomar", "नितिन तोमर", "up-yoddhas",
                "15 रेड अंक — अंतिम मिनटों की सुपर रेड ने भारत को जिताया"),
        rosterA=[
            _ar("nitin-tomar", "Nitin Tomar", "नितिन तोमर", "up-yoddhas", "raider"),
            _ar("pardeep-narwal", "Pardeep Narwal", "प्रदीप नरवाल", "patna-pirates", "raider"),
            _ar("deepak-niwas-hooda", "Deepak Niwas Hooda", "दीपक निवास हुड्डा", "jaipur-pink-panthers", "allrounder"),
            _ar("rohit-kumar", "Rohit Kumar", "रोहित कुमार", "bengaluru-bulls", "raider"),
            _ar("monu-goyat", "Monu Goyat", "मोनू गोयत", "haryana-steelers", "raider"),
            _ar("surender-nada", "Surender Nada", "सुरेंदर नाडा", "haryana-steelers", "defender"),
            _ar("girish-ernak", "Girish Ernak", "गिरीश एरनाक", "u-mumba", "defender"),
            _ar("sandeep-narwal", "Sandeep Narwal", "संदीप नरवाल", "patna-pirates", "allrounder"),
        ],
        rosterB=[
            _ar("fazel-atrachali", "Fazel Atrachali", "फ़ज़ेल अत्राचली", "u-mumba", "defender"),
            _ar("meraj-sheykh", "Meraj Sheykh", "मेराज शेख़", "dabang-delhi", "allrounder"),
            _ar("jang-kun-lee", "Jang Kun Lee", "जांग कुन ली", "bengal-warriors", "raider"),
            _ar("mohammad-nabibakhsh", "Mohammad Nabibakhsh", "मोहम्मद नबीबख़्श", "bengal-warriors", "allrounder"),
            _ar("abozar-mighani", "Abozar Mighani", "अबोज़र मिघानी", "telugu-titans", "defender"),
            _ar("hadi-tajik", "Hadi Tajik", "हादी ताजिक", "u-mumba", "defender"),
            _ar("gholamabbas-korouki", "Gholamabbas Korouki", "गुलामअब्बास कोरूकी", "tamil-thalaivas", "defender"),
            _ar("heidarali-ekrami", "Heidarali Ekrami", "हेदरअली एकरामी", "telugu-titans", "defender"),
        ],
        performers=[
            _ap("nitin-tomar", "Nitin Tomar", "नितिन तोमर", "up-yoddhas",
                "15 रेड अंक — मैच के सर्वश्रेष्ठ खिलाड़ी (MVP)"),
            _ap("meraj-sheykh", "Meraj Sheykh", "मेराज शेख़", "dabang-delhi",
                "11 रेड अंक — विश्व ऑल-स्टार्स के कप्तान और अग्रणी रेडर"),
            _ap("fazel-atrachali", "Fazel Atrachali", "फ़ज़ेल अत्राचली", "u-mumba",
                "6 टैकल अंक — 'सुल्तान' की दीवार जैसी रक्षा"),
            _ap("pardeep-narwal", "Pardeep Narwal", "प्रदीप नरवाल", "patna-pirates",
                "12 रेड अंक — डुबकी और लगातार बोनस अंक"),
        ],
        note="सीज़न 6 (2018) के प्रदर्शनी शोकेस में भारतीय सितारों ने विदेशी (विश्व) सितारों "
             "से टक्कर ली। एक ओर प्रदीप नरवाल, नितिन तोमर और दीपक हुड्डा जैसे भारतीय दिग्गज थे, "
             "तो दूसरी ओर फ़ज़ेल अत्राचली, मेराज शेख़ और जांग कुन ली जैसे विदेशी सितारे। "
             "रोमांचक मुक़ाबले में भारतीय ऑल-स्टार्स ने नितिन तोमर की आख़िरी क्षणों की सुपर रेड "
             "के दम पर 41–39 से जीत दर्ज की। इस मैच ने पीकेएल के अंतरराष्ट्रीय आकर्षण और "
             "विदेशी खिलाड़ियों की बढ़ती भूमिका को रेखांकित किया।"),
]
